'use strict';function A(h,a,b,g){h.M.be(h.cc,a,b,g,void 0)}function B(h,a,b){return h.M.Mf(h.cc,a,b,void 0,void 0)}function D(h,a,b,g){h.M.hb?A(h,a,b,g):h.M.oj()._OnMessageFromDOM({type:"event",component:h.cc,handler:a,dispatchOpts:g||null,data:b,responseId:null})}function E(h,a,b){h.M.R(h.cc,a,b)}function F(h,a){for(const [b,g]of a)E(h,b,g)}function G(h){h.ud||(h.M.Yi(h.Og),h.ud=!0)}window.Bb=class{constructor(h,a){this.M=h;this.cc=a;this.ud=!1;this.Og=()=>this.la()}wf(){}la(){}};
function H(h){-1!==h.Sb&&(self.clearTimeout(h.Sb),h.Sb=-1)}window.si=class{constructor(h,a){this.Ke=h;this.ml=a;this.Sb=-1;this.vd=-Infinity;this.Pg=()=>{this.Sb=-1;this.vd=Date.now();this.jc=!0;this.Ke();this.jc=!1};this.qg=this.jc=!1}l(){H(this);this.Pg=this.Ke=null}};"use strict";
function I(h,a){const b=a.elementId,g=h.Df(b,a);h.Ba.set(b,g);a.isVisible||(g.style.display="none");g.addEventListener("focus",()=>{K(h,"elem-focused",b)});g.addEventListener("blur",()=>{K(h,"elem-blurred",b)});h.kd&&document.body.appendChild(g)}function L(h,a,b){E(h,a,g=>{const k=h.Ba.get(g.elementId);return b(k,g)})}function K(h,a,b,g){g||(g={});g.elementId=b;A(h,a,g)}function M(h,a,b){var g;g||(g={});g.elementId=b;D(h,a,g)}
window.zh=class extends self.Bb{constructor(h,a){super(h,a);this.Ba=new Map;this.kd=!0;F(this,[["create",b=>I(this,b)],["destroy",b=>{{b=b.elementId;const g=this.Ba.get(b);this.kd&&g.parentElement.removeChild(g);this.Ba.delete(b)}}],["set-visible",b=>{this.kd&&(this.Ba.get(b.elementId).style.display=b.isVisible?"":"none")}],["update-position",b=>{if(this.kd){var g=this.Ba.get(b.elementId);g.style.left=b.left+"px";g.style.top=b.top+"px";g.style.width=b.width+"px";g.style.height=b.height+"px";b=b.fontSize;
null!==b&&(g.style.fontSize=b+"em")}}],["update-state",b=>{{const g=this.Ba.get(b.elementId);this.ne(g,b)}}],["focus",b=>this.Ee(b)],["set-css-style",b=>{this.Ba.get(b.elementId).style[b.prop]=b.val}],["set-attribute",b=>{this.Ba.get(b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{this.Ba.get(b.elementId).removeAttribute(b.name)}]]);L(this,"get-element",b=>b)}Df(){throw Error("required override");}ne(){throw Error("required override");}Ee(h){var a=this.Ba.get(h.elementId);h.focus?
a.focus():a.blur()}};"use strict";
{const h=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);function a(z){if(z.yl){const q=document.createElement("script");q.async=!1;q.textContent=z.Bl;document.head.appendChild(q)}else return new Promise((q,r)=>{const f=document.createElement("script");f.onload=q;f.onerror=r;f.async=!1;f.src=z;document.head.appendChild(f)})}let b=new Audio;const g={"audio/webm; codecs=opus":!!b.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!b.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!b.canPlayType("audio/webm; codecs=vorbis"),
"audio/ogg; codecs=vorbis":!!b.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!b.canPlayType("audio/mp4"),"audio/mpeg":!!b.canPlayType("audio/mpeg")};b=null;async function k(z){z=await w(z);return(new TextDecoder("utf-8")).decode(z)}function w(z){return new Promise((q,r)=>{const f=new FileReader;f.onload=l=>q(l.target.result);f.onerror=l=>r(l);f.readAsArrayBuffer(z)})}const n=[];let e=0;window.RealFile=window.File;const m=[],c=new Map,d=new Map;let p=0;const v=[];self.Nl=function(z){if("function"!==
typeof z)throw Error("runOnStartup called without a function");v.push(z)};const x=new Set(["cordova","playable-ad","instant-games"]);window.kb=class z{constructor(q){this.hb=q.Dl;this.eb=null;this.fa="";this.Gd=q.Al;this.Lc={};this.cb=this.Kb=this.Kc=null;this.qd=[];this.qc=this.ca=this.Qb=null;this.Pb=-1;this.sl=()=>this.bk();this.Ob=[];this.T=q.Qg;!this.hb||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation||(this.hb=!1);x.has(this.T)&&this.hb&&(console.warn("[C3 runtime] Worker mode is enabled and supported, but is disabled in WebViews due to crbug.com/923007. Reverting to DOM mode."),
this.hb=!1);this.Ad=this.Ta=null;"html5"!==this.T&&"playable-ad"!==this.T||"file"!==location.protocol.substr(0,4)||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");this.R("runtime","cordova-fetch-local-file",r=>this.Ej(r));this.R("runtime","create-job-worker",()=>this.Fj());"cordova"===this.T?document.addEventListener("deviceready",()=>this.ag(q)):this.ag(q)}l(){this.pe();this.eb&&(this.eb=
this.eb.onmessage=null);this.Kc&&(this.Kc.terminate(),this.Kc=null);this.Kb&&(this.Kb.l(),this.Kb=null);this.ca&&(this.ca.parentElement.removeChild(this.ca),this.ca=null)}Kf(){return h&&"cordova"===this.T}Uc(){return h&&x.has(this.T)||navigator.standalone}async ag(q){"preview"===this.T&&(this.cb=document.createElement("div"),this.cb.className="previewLoadingMessage",this.cb.textContent=q.Ll,document.body.appendChild(this.cb));if("playable-ad"===this.T){this.Ta=self.c3_base64files;this.Ad={};await this.cj();
for(let f=0,l=q.Ub.length;f<l;++f){var r=q.Ub[f].toLowerCase();this.Ad.hasOwnProperty(r)?q.Ub[f]={yl:!0,Bl:this.Ad[r]}:this.Ta.hasOwnProperty(r)&&(q.Ub[f]=URL.createObjectURL(this.Ta[r]))}}q.vl?this.fa=q.vl:(r=location.origin,this.fa=("null"===r?"file:///":r)+location.pathname,r=this.fa.lastIndexOf("/"),-1!==r&&(this.fa=this.fa.substr(0,r+1)));if(q.Fl)for(const [f,l]of Object.entries(q.Fl))this.Lc[f]=URL.createObjectURL(l);r=new MessageChannel;this.eb=r.port1;this.eb.onmessage=f=>this._OnMessageFromRuntime(f.data);
window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(f=>this.Uj(f));this.qc=new self.ci(this);await N(this.qc);this.Lf();"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();this.hb?await this.uj(q,r.port2):await this.tj(q,r.port2)}se(q){return this.Lc.hasOwnProperty(q)?this.Lc[q]:q.endsWith("/workermain.js")&&this.Lc.hasOwnProperty("workermain.js")?this.Lc["workermain.js"]:"playable-ad"===this.T&&
this.Ta.hasOwnProperty(q.toLowerCase())?URL.createObjectURL(this.Ta[q.toLowerCase()]):q}async Td(q,r,f){if(q.startsWith("blob:"))return new Worker(q,f);if(this.Kf()&&"file:"===location.protocol)return q=await this.Sd(this.Gd+q),new Worker(URL.createObjectURL(new Blob([q],{type:"application/javascript"})),f);q=new URL(q,r);if(location.origin!==q.origin){q=await fetch(q);if(!q.ok)throw Error("failed to fetch worker script");q=await q.blob();return new Worker(URL.createObjectURL(q),f)}return new Worker(q,
f)}nb(){return Math.max(window.innerWidth,1)}mb(){return Math.max(window.innerHeight,1)}Lf(){if(this.Uc()){const q=document.documentElement.style,r=document.body.style,f=window.innerWidth<window.innerHeight,l=f?window.screen.width:window.screen.height;r.height=q.height=(f?window.screen.height:window.screen.width)+"px";r.width=q.width=l+"px"}}$f(q){var r=this.qc;return{baseUrl:this.fa,windowInnerWidth:this.nb(),windowInnerHeight:this.mb(),devicePixelRatio:window.devicePixelRatio,isFullscreen:z.Zd(),
projectData:q.Ml,previewImageBlobs:window.cr_previewImageBlobs||this.Ta,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,exportType:q.Qg,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.Kl,jobScheduler:{inputPort:r.We,outputPort:r.hf,maxNumWorkers:r.ol},supportedAudioFormats:g,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.Gd+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.Gd+"opus.wasm.wasm",isiOSCordova:this.Kf(),isiOSWebView:this.Uc(),isFBInstantAvailable:"undefined"!==
typeof self.FBInstant}}async uj(q,r){var f=this.se(q.El);this.Kc=await this.Td(f,this.fa,{name:"Runtime"});this.ca=document.createElement("canvas");this.ca.style.display="none";f=this.ca.transferControlToOffscreen();document.body.appendChild(this.ca);window.c3canvas=this.ca;this.Kc.postMessage(Object.assign(this.$f(q),{type:"init-runtime",isInWorker:!0,messagePort:r,canvas:f,workerDependencyScripts:q.uf||[],engineScripts:q.Ub,projectScripts:window.Jl,projectScriptsStatus:self.C3_ProjectScriptsStatus}),
[r,f,...O(this.qc)]);this.qd=m.map(l=>new l(this));this.Zf();self.c3_callFunction=(l,u)=>this.Qb.vj(l,u);"preview"===this.T&&(self.goToLastErrorScript=()=>this.be("runtime","go-to-last-error-script"))}async tj(q,r){this.ca=document.createElement("canvas");this.ca.style.display="none";document.body.appendChild(this.ca);window.c3canvas=this.ca;this.qd=m.map(l=>new l(this));this.Zf();const f=q.Ub.map(l=>"string"===typeof l?(new URL(l,this.fa)).toString():l);Array.isArray(q.uf)&&f.unshift(...q.uf);await Promise.all(f.map(l=>
a(l)));if(q.Xg&&0<q.Xg.length){const l=self.C3_ProjectScriptsStatus;try{if(await Promise.all(q.Xg.map(u=>a(u[1]))),Object.values(l).some(u=>!u)){self.setTimeout(()=>this.kg(l),100);return}}catch(u){console.error("[Preview] Error loading project scripts: ",u);self.setTimeout(()=>this.kg(l),100);return}}"preview"===this.T&&"object"!==typeof self.Gl.Hl?(this.fd(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):
(q=Object.assign(this.$f(q),{isInWorker:!1,messagePort:r,canvas:this.ca,runOnStartupFunctions:v}),this.cg(),this.Kb=self.C3_CreateRuntime(q),await self.C3_InitRuntime(this.Kb,q))}kg(q){this.fd();q=`Failed to load project script '${Object.entries(q).filter(r=>!r[1]).map(r=>r[0])[0]}'. Check all your JavaScript code has valid syntax.`;console.error("[Preview] "+q);alert(q)}cg(){this.fd()}fd(){this.cb&&(this.cb.parentElement.removeChild(this.cb),this.cb=null)}async Fj(){const q=await P(this.qc);return{outputPort:q,
transferables:[q]}}oj(){if(this.hb)throw Error("not available in worker mode");return this.Kb}be(q,r,f,l,u){this.eb.postMessage({type:"event",component:q,handler:r,dispatchOpts:l||null,data:f,responseId:null},u)}Mf(q,r,f,l,u){const t=p++,y=new Promise((C,J)=>{d.set(t,{resolve:C,reject:J})});this.eb.postMessage({type:"event",component:q,handler:r,dispatchOpts:l||null,data:f,responseId:t},u);return y}["_OnMessageFromRuntime"](q){const r=q.type;if("event"===r)return this.Kj(q);if("result"===r)this.ek(q);
else if("runtime-ready"===r)this.fk();else if("alert-error"===r)this.fd(),alert(q.message);else if("creating-runtime"===r)this.cg();else throw Error(`unknown message '${r}'`);}Kj(q){const r=q.component,f=q.handler,l=q.data,u=q.responseId;if(q=c.get(r))if(q=q.get(f)){var t=null;try{t=q(l)}catch(y){console.error(`Exception in '${r}' handler '${f}':`,y);null!==u&&this.dd(u,!1,""+y);return}if(null===u)return t;t&&t.then?t.then(y=>this.dd(u,!0,y)).catch(y=>{console.error(`Rejection from '${r}' handler '${f}':`,
y);this.dd(u,!1,""+y)}):this.dd(u,!0,t)}else console.warn(`[DOM] No handler '${f}' for component '${r}'`);else console.warn(`[DOM] No event handlers for component '${r}'`)}dd(q,r,f){let l;f&&f.transferables&&(l=f.transferables);this.eb.postMessage({type:"result",responseId:q,isOk:r,result:f},l)}ek(q){const r=q.responseId,f=q.isOk;q=q.result;const l=d.get(r);f?l.resolve(q):l.reject(q);d.delete(r)}R(q,r,f){let l=c.get(q);l||(l=new Map,c.set(q,l));if(l.has(r))throw Error(`[DOM] Component '${q}' already has handler '${r}'`);
l.set(r,f)}static Ab(q){if(m.includes(q))throw Error("DOM handler already added");m.push(q)}Zf(){for(const q of this.qd)if("runtime"===q.cc){this.Qb=q;return}throw Error("cannot find runtime DOM handler");}Uj(q){this.be("debugger","message",q)}fk(){for(const q of this.qd)q.wf()}static Zd(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement)}Yi(q){this.Ob.push(q);this.He()}Hk(q){q=this.Ob.indexOf(q);if(-1===q)throw Error("invalid callback");this.Ob.splice(q,
1);this.Ob.length||this.pe()}He(){-1===this.Pb&&this.Ob.length&&(this.Pb=requestAnimationFrame(this.sl))}pe(){-1!==this.Pb&&(cancelAnimationFrame(this.Pb),this.Pb=-1)}bk(){this.Pb=-1;for(const q of this.Ob)q();this.He()}lb(q){this.Qb.lb(q)}Eb(q){this.Qb.Eb(q)}Ge(){this.Qb.Ge()}Yc(q){this.Qb.Yc(q)}$h(){return!!g["audio/webm; codecs=opus"]}async kl(q){q=await this.Mf("runtime","opus-decode",{arrayBuffer:q},null,[q]);return new Float32Array(q)}Zh(q){return/^(?:[a-z]+:)?\/\//.test(q)||"data:"===q.substr(0,
5)||"blob:"===q.substr(0,5)}ai(q){return!this.Zh(q)}async Ej(q){const r=q.filename;switch(q.as){case "text":return await this.yh(r);case "buffer":return await this.Sd(r);default:throw Error("unsupported type");}}Cf(q){const r=window.cordova.file.applicationDirectory+"www/"+q.toLowerCase();return new Promise((f,l)=>{window.resolveLocalFileSystemURL(r,u=>{u.file(f,l)},l)})}async yh(q){q=await this.Cf(q);return await k(q)}qe(){if(n.length&&!(8<=e)){e++;var q=n.shift();this.dj(q.filename,q.Cl,q.xl)}}Sd(q){return new Promise((r,
f)=>{n.push({filename:q,Cl:l=>{e--;this.qe();r(l)},xl:l=>{e--;this.qe();f(l)}});this.qe()})}async dj(q,r,f){try{const l=await this.Cf(q),u=await w(l);r(u)}catch(l){f(l)}}async cj(){const q=[];for(const [r,f]of Object.entries(this.Ta))q.push(this.bj(r,f));await Promise.all(q)}async bj(q,r){if("object"===typeof r)this.Ta[q]=new Blob([r.str],{type:r.type}),this.Ad[q]=r.str;else{let f=await this.lj(r);f||(f=this.fj(r));this.Ta[q]=f}}async lj(q){try{return await (await fetch(q)).blob()}catch(r){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
r),null}}fj(q){q=this.Ak(q);return this.aj(q.data,q.zl)}Ak(q){var r=q.indexOf(",");if(0>r)throw new URIError("expected comma in data: uri");var f=q.substring(r+1);r=q.substring(5,r).split(";");q=r[0]||"";const l=r[2];f="base64"===r[1]||"base64"===l?atob(f):decodeURIComponent(f);return{zl:q,data:f}}aj(q,r){var f=q.length;let l=f>>2,u=new Uint8Array(f),t=new Uint32Array(u.buffer,0,l),y,C;for(C=y=0;y<l;++y)t[y]=q.charCodeAt(C++)|q.charCodeAt(C++)<<8|q.charCodeAt(C++)<<16|q.charCodeAt(C++)<<24;for(f&=
3;f--;)u[C]=q.charCodeAt(C),++C;return new Blob([u],{type:r})}}}"use strict";
{const h=self.kb;function a(f){return f.sourceCapabilities&&f.sourceCapabilities.firesTouchEvents||f.originalEvent&&f.originalEvent.sourceCapabilities&&f.originalEvent.sourceCapabilities.firesTouchEvents}const b=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),g={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},k={dispatchUserScriptEvent:!0},w={dispatchRuntimeEvent:!0};function n(f){return new Promise((l,u)=>{const t=document.createElement("link");t.onload=()=>l(t);t.onerror=y=>u(y);t.rel=
"stylesheet";t.href=f;document.head.appendChild(t)})}function e(f){return new Promise((l,u)=>{const t=new Image;t.onload=()=>l(t);t.onerror=y=>u(y);t.src=f})}async function m(f){f=URL.createObjectURL(f);try{return await e(f)}finally{URL.revokeObjectURL(f)}}function c(f){return new Promise((l,u)=>{let t=new FileReader;t.onload=y=>l(y.target.result);t.onerror=y=>u(y);t.readAsText(f)})}async function d(f,l,u){if(!/firefox/i.test(navigator.userAgent))return await m(f);var t=await c(f);t=(new DOMParser).parseFromString(t,
"image/svg+xml");const y=t.documentElement;if(y.hasAttribute("width")&&y.hasAttribute("height")){const C=y.getAttribute("width"),J=y.getAttribute("height");if(!C.includes("%")&&!J.includes("%"))return await m(f)}y.setAttribute("width",l+"px");y.setAttribute("height",u+"px");t=(new XMLSerializer).serializeToString(t);f=new Blob([t],{type:"image/svg+xml"});return await m(f)}function p(f){do{if(f.parentNode&&f.hasAttribute("contenteditable"))return!0;f=f.parentNode}while(f);return!1}const v=new Set(["canvas",
"body","html"]);function x(f){v.has(f.target.tagName.toLowerCase())&&f.preventDefault()}function z(f){(f.metaKey||f.ctrlKey)&&f.preventDefault()}self.C3_GetSvgImageSize=async function(f){f=await m(f);if(0<f.width&&0<f.height)return[f.width,f.height];{f.style.position="absolute";f.style.left="0px";f.style.top="0px";f.style.visibility="hidden";document.body.appendChild(f);const l=f.getBoundingClientRect();document.body.removeChild(f);return[l.width,l.height]}};self.C3_RasterSvgImageBlob=async function(f,
l,u,t,y){f=await d(f,l,u);const C=document.createElement("canvas");C.width=t;C.height=y;C.getContext("2d").drawImage(f,0,0,l,u);return C};let q=!1;document.addEventListener("pause",()=>q=!0);document.addEventListener("resume",()=>q=!1);function r(){try{return window.parent&&window.parent.document.hasFocus()}catch(f){return!1}}h.Ab(class extends self.Bb{constructor(f){super(f,"runtime");this.xg=!0;this.Rb=-1;this.pf="any";this.lg=this.mg=!1;this.$e=this.Cc=this.ub=null;f.R("canvas","update-size",t=>
this.yk(t));f.R("runtime","invoke-download",t=>this.Rj(t));f.R("runtime","raster-svg-image",t=>this.ck(t));f.R("runtime","get-svg-image-size",t=>this.Nj(t));f.R("runtime","set-target-orientation",t=>this.hk(t));f.R("runtime","register-sw",()=>this.dk());f.R("runtime","post-to-debugger",t=>this.gg(t));f.R("runtime","go-to-script",t=>this.gg(t));f.R("runtime","before-start-ticking",()=>this.Bj());f.R("runtime","debug-highlight",t=>this.Gj(t));f.R("runtime","enable-device-orientation",()=>this.$i());
f.R("runtime","enable-device-motion",()=>this.Zi());f.R("runtime","add-stylesheet",t=>this.zj(t));f.R("runtime","alert",t=>this.xe(t));f.R("runtime","hide-cordova-splash",()=>this.Oj());const l=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",t=>{const y=t.target;l.has(y.tagName.toLowerCase())||p(y)||t.preventDefault()});const u=f.ca;window.addEventListener("selectstart",x);window.addEventListener("gesturehold",x);u.addEventListener("selectstart",x);u.addEventListener("gesturehold",
x);window.addEventListener("touchstart",x,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",x,{passive:!1}),u.addEventListener("pointerdown",x)):u.addEventListener("touchstart",x);this.vc=0;window.addEventListener("mousedown",t=>{1===t.button&&t.preventDefault()});window.addEventListener("mousewheel",z,{passive:!1});window.addEventListener("wheel",z,{passive:!1});window.addEventListener("resize",()=>this.zk());f.Uc()&&window.addEventListener("focusout",()=>{{const C=
document.activeElement;if(C){var t=C.tagName.toLowerCase();var y=new Set("email number password search tel text url".split(" "));t="textarea"===t?!0:"input"===t?y.has(C.type.toLowerCase()||"text"):p(C)}else t=!1}t||(document.scrollingElement.scrollTop=0)});this.Lb=new Set;this.Bd=new WeakSet;this.bb=!1}Bj(){"cordova"===this.M.T?(document.addEventListener("pause",()=>this.Fe(!0)),document.addEventListener("resume",()=>this.Fe(!1))):document.addEventListener("visibilitychange",()=>this.Fe(document.hidden));
return{isSuspended:!(!document.hidden&&!q)}}wf(){window.addEventListener("focus",()=>this.ed("window-focus"));window.addEventListener("blur",()=>{this.ed("window-blur",{parentHasFocus:r()});this.vc=0});window.addEventListener("fullscreenchange",()=>this.Ae());window.addEventListener("webkitfullscreenchange",()=>this.Ae());window.addEventListener("mozfullscreenchange",()=>this.Ae());window.addEventListener("fullscreenerror",l=>this.Be(l));window.addEventListener("webkitfullscreenerror",l=>this.Be(l));
window.addEventListener("mozfullscreenerror",l=>this.Be(l));window.addEventListener("keydown",l=>this.dg("keydown",l));window.addEventListener("keyup",l=>this.dg("keyup",l));window.addEventListener("dblclick",l=>this.Ce("dblclick",l,g));window.addEventListener("wheel",l=>this.Wj(l));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",l=>{this.te(l);this.ac("pointerdown",l)}),this.M.hb&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.Cc=new self.si(()=>this.jj(),
5),this.Cc.qg=!0,window.addEventListener("pointerrawupdate",l=>this.$j(l))):window.addEventListener("pointermove",l=>this.ac("pointermove",l)),window.addEventListener("pointerup",l=>this.ac("pointerup",l)),window.addEventListener("pointercancel",l=>this.ac("pointercancel",l))):(window.addEventListener("mousedown",l=>{this.te(l);this.De("pointerdown",l)}),window.addEventListener("mousemove",l=>this.De("pointermove",l)),window.addEventListener("mouseup",l=>this.De("pointerup",l)),window.addEventListener("touchstart",
l=>{this.te(l);this.cd("pointerdown",l)}),window.addEventListener("touchmove",l=>this.cd("pointermove",l)),window.addEventListener("touchend",l=>this.cd("pointerup",l)),window.addEventListener("touchcancel",l=>this.cd("pointercancel",l)));const f=()=>this.Ge();window.addEventListener("pointerup",f,!0);window.addEventListener("touchend",f,!0);window.addEventListener("click",f,!0);window.addEventListener("keydown",f,!0);window.addEventListener("gamepadconnected",f,!0)}ed(f,l){A(this,f,l||null,w)}nb(){return this.M.nb()}mb(){return this.M.mb()}zk(){const f=
this.nb(),l=this.mb();this.ed("window-resize",{innerWidth:f,innerHeight:l,devicePixelRatio:window.devicePixelRatio});this.M.Uc()&&(-1!==this.Rb&&clearTimeout(this.Rb),this.hg(f,l,0))}Ik(f,l,u){-1!==this.Rb&&clearTimeout(this.Rb);this.Rb=setTimeout(()=>this.hg(f,l,u),48)}hg(f,l,u){const t=this.nb(),y=this.mb();this.Rb=-1;t!=f||y!=l?this.ed("window-resize",{innerWidth:t,innerHeight:y,devicePixelRatio:window.devicePixelRatio}):10>u&&this.Ik(t,y,u+1)}hk(f){this.pf=f.targetOrientation}gl(){const f=this.pf;
if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(f).catch(l=>console.warn("[Construct 3] Failed to lock orientation: ",l));else try{let l=!1;screen.lockOrientation?l=screen.lockOrientation(f):screen.webkitLockOrientation?l=screen.webkitLockOrientation(f):screen.mozLockOrientation?l=screen.mozLockOrientation(f):screen.msLockOrientation&&(l=screen.msLockOrientation(f));l||console.warn("[Construct 3] Failed to lock orientation")}catch(l){console.warn("[Construct 3] Failed to lock orientation: ",
l)}}Ae(){const f=h.Zd();f&&"any"!==this.pf&&this.gl();A(this,"fullscreenchange",{isFullscreen:f,innerWidth:this.nb(),innerHeight:this.mb()})}Be(f){console.warn("[Construct 3] Fullscreen request failed: ",f);A(this,"fullscreenerror",{isFullscreen:h.Zd(),innerWidth:this.nb(),innerHeight:this.mb()})}Fe(f){f?this.M.pe():this.M.He();A(this,"visibilitychange",{hidden:f})}dg(f,l){"Backspace"===l.key&&x(l);const u=b.get(l.code)||l.code;D(this,f,{code:u,key:l.key,which:l.which,repeat:l.repeat,altKey:l.altKey,
ctrlKey:l.ctrlKey,metaKey:l.metaKey,shiftKey:l.shiftKey,timeStamp:l.timeStamp},g)}Wj(f){A(this,"wheel",{clientX:f.clientX,clientY:f.clientY,pageX:f.pageX,pageY:f.pageY,deltaX:f.deltaX,deltaY:f.deltaY,deltaZ:f.deltaZ,deltaMode:f.deltaMode,timeStamp:f.timeStamp},g)}Ce(f,l,u){a(l)||D(this,f,{button:l.button,buttons:l.buttons,clientX:l.clientX,clientY:l.clientY,pageX:l.pageX,pageY:l.pageY,timeStamp:l.timeStamp},u)}De(f,l){if(!a(l)){var u=this.vc;"pointerdown"===f&&0!==u?f="pointermove":"pointerup"===
f&&0!==l.buttons&&(f="pointermove");D(this,f,{pointerId:1,pointerType:"mouse",button:l.button,buttons:l.buttons,lastButtons:u,clientX:l.clientX,clientY:l.clientY,pageX:l.pageX,pageY:l.pageY,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:l.timeStamp},g);this.vc=l.buttons;this.Ce(l.type,l,k)}}ac(f,l){if(this.Cc&&"pointermove"!==f){var u=this.Cc;u.jc||(H(u),u.vd=Date.now())}u=0;"mouse"===l.pointerType&&(u=this.vc);D(this,f,{pointerId:l.pointerId,pointerType:l.pointerType,
button:l.button,buttons:l.buttons,lastButtons:u,clientX:l.clientX,clientY:l.clientY,pageX:l.pageX,pageY:l.pageY,width:l.width||0,height:l.height||0,pressure:l.pressure||0,tangentialPressure:l.tangentialPressure||0,tiltX:l.tiltX||0,tiltY:l.tiltY||0,twist:l.twist||0,timeStamp:l.timeStamp},g);"mouse"===l.pointerType&&(u="mousemove","pointerdown"===f?u="mousedown":"pointerup"===f&&(u="pointerup"),this.Ce(u,l,k),this.vc=l.buttons)}$j(f){this.$e=f;f=this.Cc;if(-1===f.Sb){var l=Date.now(),u=l-f.vd,t=f.ml;
u>=t&&f.qg?(f.vd=l,f.jc=!0,f.Ke(),f.jc=!1):f.Sb=self.setTimeout(f.Pg,Math.max(t-u,4))}}jj(){this.ac("pointermove",this.$e);this.$e=null}cd(f,l){for(let u=0,t=l.changedTouches.length;u<t;++u){const y=l.changedTouches[u];D(this,f,{pointerId:y.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:y.clientX,clientY:y.clientY,pageX:y.pageX,pageY:y.pageY,width:2*(y.radiusX||y.webkitRadiusX||0),height:2*(y.radiusY||y.webkitRadiusY||0),pressure:y.force||y.webkitForce||0,tangentialPressure:0,
tiltX:0,tiltY:0,twist:y.rotationAngle||0,timeStamp:l.timeStamp},g)}}te(f){window!==window.top&&window.focus();this.bg(f.target)&&document.activeElement&&!this.bg(document.activeElement)&&document.activeElement.blur()}bg(f){return!f||f===document||f===window||f===document.body||"canvas"===f.tagName.toLowerCase()}$i(){this.mg||(this.mg=!0,window.addEventListener("deviceorientation",f=>this.Ij(f)),window.addEventListener("deviceorientationabsolute",f=>this.Jj(f)))}Zi(){this.lg||(this.lg=!0,window.addEventListener("devicemotion",
f=>this.Hj(f)))}Ij(f){A(this,"deviceorientation",{absolute:!!f.absolute,alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0,timeStamp:f.timeStamp,webkitCompassHeading:f.webkitCompassHeading,webkitCompassAccuracy:f.webkitCompassAccuracy},g)}Jj(f){A(this,"deviceorientationabsolute",{absolute:!!f.absolute,alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0,timeStamp:f.timeStamp},g)}Hj(f){let l=null;var u=f.acceleration;u&&(l={x:u.x||0,y:u.y||0,z:u.z||0});u=null;var t=f.accelerationIncludingGravity;t&&(u={x:t.x||
0,y:t.y||0,z:t.z||0});t=null;const y=f.rotationRate;y&&(t={alpha:y.alpha||0,beta:y.beta||0,gamma:y.gamma||0});A(this,"devicemotion",{acceleration:l,accelerationIncludingGravity:u,rotationRate:t,interval:f.interval,timeStamp:f.timeStamp},g)}yk(f){const l=this.M,u=l.ca;u.style.width=f.styleWidth+"px";u.style.height=f.styleHeight+"px";u.style.marginLeft=f.marginLeft+"px";u.style.marginTop=f.marginTop+"px";l.Lf();this.xg&&(u.style.display="",this.xg=!1)}Rj(f){const l=f.url;f=f.filename;const u=document.createElement("a"),
t=document.body;u.textContent=f;u.href=l;u.download=f;t.appendChild(u);u.click();t.removeChild(u)}async ck(f){var l=f.imageBitmapOpts;f=await self.C3_RasterSvgImageBlob(f.blob,f.imageWidth,f.imageHeight,f.surfaceWidth,f.surfaceHeight);l=l?await createImageBitmap(f,l):await createImageBitmap(f);return{imageBitmap:l,transferables:[l]}}async Nj(f){return await self.C3_GetSvgImageSize(f.blob)}async zj(f){await n(f.url)}Ge(){var f=[...this.Lb];this.Lb.clear();if(!this.bb)for(const l of f)(f=l.play())&&
f.catch(()=>{this.Bd.has(l)||this.Lb.add(l)})}lb(f){if("function"!==typeof f.play)throw Error("missing play function");this.Bd.delete(f);let l;try{l=f.play()}catch(u){this.Lb.add(f);return}l&&l.catch(()=>{this.Bd.has(f)||this.Lb.add(f)})}Eb(f){this.Lb.delete(f);this.Bd.add(f)}Yc(f){this.bb=!!f}Oj(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}Gj(f){if(f.show){this.ub||(this.ub=document.createElement("div"),this.ub.id="inspectOutline",document.body.appendChild(this.ub));
var l=this.ub;l.style.display="";l.style.left=f.left-1+"px";l.style.top=f.top-1+"px";l.style.width=f.width+2+"px";l.style.height=f.height+2+"px";l.textContent=f.name}else this.ub&&(this.ub.style.display="none")}dk(){window.C3_RegisterSW&&window.C3_RegisterSW()}gg(f){window.c3_postToMessagePort&&(f.from="runtime",window.c3_postToMessagePort(f))}vj(f,l){return B(this,"js-invoke-function",{name:f,params:l})}xe(f){alert(f.message)}})}"use strict";
async function N(h){if(h.ll)throw Error("already initialised");h.ll=!0;var a=h.Fd.se("dispatchworker.js");h.Ne=await h.Fd.Td(a,h.fa,{name:"DispatchWorker"});a=new MessageChannel;h.We=a.port1;h.Ne.postMessage({type:"_init","in-port":a.port2},[a.port2]);h.hf=await P(h)}function O(h){return[h.We,h.hf]}
async function P(h){const a=h.yg.length;var b=h.Fd.se("jobworker.js");b=await h.Fd.Td(b,h.fa,{name:"JobWorker"+a});const g=new MessageChannel,k=new MessageChannel;h.Ne.postMessage({type:"_addJobWorker",port:g.port1},[g.port1]);b.postMessage({type:"init",number:a,"dispatch-port":g.port2,"output-port":k.port2},[g.port2,k.port2]);h.yg.push(b);return k.port1}
self.ci=class{constructor(h){this.Fd=h;this.fa=h.fa;this.fa="preview"===h.T?this.fa+"c3/workers/":this.fa+h.Gd;this.ol=Math.min(navigator.hardwareConcurrency||2,16);this.Ne=null;this.yg=[];this.hf=this.We=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.kb({Dl:!0,El:"workermain.js",Ub:["scripts/c3runtime.js"],Al:"scripts/",uf:[],Qg:"html5"}));"use strict";
{function h(b){b.stopPropagation()}function a(b){13!==b.which&&27!==b.which&&b.stopPropagation()}self.kb.Ab(class extends self.zh{constructor(b){super(b,"text-input");L(this,"scroll-to-bottom",g=>this.gk(g))}Df(b,g){let k;const w=g.type;"textarea"===w?(k=document.createElement("textarea"),k.style.resize="none"):(k=document.createElement("input"),k.type=w);k.style.position="absolute";k.autocomplete="off";k.addEventListener("touchstart",h);k.addEventListener("touchmove",h);k.addEventListener("touchend",
h);k.addEventListener("mousedown",h);k.addEventListener("mouseup",h);k.addEventListener("keydown",a);k.addEventListener("keyup",a);k.addEventListener("click",n=>{n.stopPropagation();M(this,"click",b)});k.addEventListener("dblclick",n=>{n.stopPropagation();M(this,"dblclick",b)});k.addEventListener("input",()=>K(this,"change",b,{text:k.value}));g.id&&(k.id=g.id);this.ne(k,g);return k}ne(b,g){b.value=g.text;b.placeholder=g.placeholder;b.title=g.title;b.disabled=!g.isEnabled;b.readOnly=g.isReadOnly;b.spellcheck=
g.spellCheck;g=g.maxLength;0>g?b.removeAttribute("maxlength"):b.setAttribute("maxlength",g)}gk(b){b.scrollTop=b.scrollHeight}})}"use strict";
{const h=[],a=2*Math.PI;function b(e){e%=a;0>e&&(e+=a);return e}class g{constructor(e,m,c,d,p,v){this.kc=e;this.lc=m;this.fb=c;this.$=d;this.Md=p;this.rg=v}Db(){return{tag:this.$,interp:this.lc,userData:this.Md,cvt:this.rg}}Za(){return this.lc}Xh(){return"undefined"!==typeof this.Md}Af(e){switch(this.fb){case 0:return e;case 1:return Math.fround(e);case 2:return 2===this.lc&&(e=b(e),e/=Math.PI,e=32767*(e-1)),e|=0,-32768>e?-32768:32767<e?32767:e;case 3:return 2===this.lc&&(e=b(e),e/=a,e*=255),e|=0,
0>e?0:255<e?255:e;default:return e}}Uf(e,m,c){switch(this.fb){case 0:e.setFloat64(m,c);m+=8;break;case 1:e.setFloat32(m,c);m+=4;break;case 2:e.setInt16(m,c);m+=2;break;case 3:e.setUint8(m,c);m+=1;break;default:e.setFloat32(m,c),m+=4}return m}Vc(e){if(2!==this.lc)return e;2===this.fb?e=(e/32767+1)*Math.PI:3===this.fb&&(e=e/255*a);return e}static Rc(e,m,c,d,p){switch(e){case 0:return p?c:m;case 1:return m+d*(c-m);case 2:return m===c?e=0:(e=Math.sin(m)*Math.sin(c)+Math.cos(m)*Math.cos(c),e=1<=e?0:-1>=
e?Math.PI:Math.acos(e)),m=0>=Math.cos(c)*Math.sin(m)-Math.sin(c)*Math.cos(m)?b(m+e*d):b(m-e*d);default:return p?c:m}}}class k{constructor(e,m){this.timestamp=e;this.data=m}}class w{constructor(e,m,c){this.ua=e;this.b=e.b;this.H=m;this.U=c;this._data=[];this._data.length=this.ua.xa.length;this.bf=this.wd=0;this.wg=this.Kd=!1;this.aa=[];this.L=this.C=this.Ea=null}Db(){var e=[];for(let c=0,d=this.ua.xa.length;c<d;++c)e.push(this.Za(this.ua.Hd,c));e={id:this.H,nid:this.U,isTimedOut:this.bi(),interpValues:e,
latestUpdate:null};const m=this.Nh();m&&(e.latestUpdate={timestamp:m.timestamp,data:m.data});return e}Of(e){this.wg=!!e}me(e,m){e=e.netValues;var c=this.ua.xa;const d=c.length;this.Kd=!1;for(let p=0;p<d;++p){const v=c[p].Af(e[p]);this._data[p]!==v&&(this._data[p]=v,this.wd=m,this.ua.Ai(m))}e=m-this.wd;m-=this.bf;c=this.ua.ng;(this.Kd=100>e&&0===c?!0:1E3>e&&1>=c?95<=m:495<=m)&&this.ua.Yh()}oe(e,m,c){const d=this.ua.xa;this.bf=c;e.setUint16(m,this.U);m+=2;for(let p=0,v=this._data.length;p<v;++p)m=d[p].Uf(e,
m,this._data[p]);return m}Qd(e,m){for(let c=0,d=this.aa.length;c<d;++c){const p=this.aa[c];if(p.timestamp===e)return;if(p.timestamp>e){this.aa.splice(c,0,new k(e,m));return}}this.aa.push(new k(e,m))}bi(){return 0===this.aa.length?!1:this.aa[this.aa.length-1].timestamp<this.ua.Hd-3E3}la(){for(;2<this.aa.length&&this.aa[0]!==this.Ea&&this.aa[0]!==this.C&&this.aa[0]!==this.L;)this.aa.shift();const e=this.ua.Hd;if(!(this.L&&this.L.timestamp>e&&this.C&&this.C.timestamp<e)){this.L=null;for(let m=0,c=this.aa.length;m<
c;++m){const d=this.aa[m];if(d.timestamp<=e){if(!this.C||d.timestamp>this.C.timestamp)this.Ea=this.C,this.C=d}else{this.L=d;break}}}}Nh(){return 0===this.aa.length?null:this.aa[this.aa.length-1]}Za(e,m){if(!this.L&&!this.C)return 0;if(this.L&&!this.C)return this.L.data[m];const c=this.ua.xa;let d,p,v;if(!this.L&&this.C){if(this.Ea){var x=this.Ea.timestamp;d=this.Ea.data[m];p=this.C.timestamp;v=this.C.data[m];e>this.C.timestamp+this.ua.sd&&(e=this.C.timestamp+this.ua.sd);x=x===p?0:(e-x)/(p-x);return g.Rc(c[m].Za(),
d,v,x,!0)}return this.C.data[m]}x=this.C.timestamp;d=this.C.data[m];p=this.L.timestamp;v=this.L.data[m];x=x===p?0:(e-x)/(p-x);return g.Rc(c[m].Za(),d,v,x,!1)}}class n{constructor(e,m,c,d){this.b=e;this.Gc=m;this.Hc=c;this.U=this.b.Rh();this.ng=d;this.Md={};this.Ma=0;this.sd=250;switch(this.ng){case 1:this.sd=500;break;case 2:this.sd=2500}this.xa=[];this.Ca=[];this.vb=new Map;this.Tb=new Set;this.yc=this.bf=this.wd=this.wc=0;this.Ib=!1;this.nd=[];this.xc=new Map;this.Hd=0;this.b.bh(this)}pb(e){this.U=
e}Ai(e){this.wd=e}Yh(){this.yc++}Rk(){this.Ib=!0}Ya(e,m,c,d,p){e=new g(this.xa.length,e,m,c,d,p);switch(m){case 0:this.Ma+=8;break;case 1:this.Ma+=4;break;case 2:this.Ma+=2;break;case 3:this.Ma+=1}this.xa.push(e)}Qd(e,m,c){this.Ph(m).Qd(e,c)}la(){this.Hd=this.b.Qc();for(const e of this.Ca)e.la()}Qh(){const e=[];for(const m of this.xa){const c={tag:m.$,precision:m.fb,interp:m.Za(),clientvaluetag:m.rg};m.Xh()&&(c.userdata=m.Md);e.push(c)}return e}Ci(e){this.Ma=this.xa.length=0;for(const m of e)this.Ya(m.interp,
m.precision,m.tag,m.userdata,m.clientvaluetag)}Ph(e){let m=this.xc.get(e);if(m)return m;m=new w(this,-1,e);this.xc.set(e,m);this.Ca.push(m);return m}Oh(e){let m=this.vb.get(e);if(m)return m;m=new w(this,e,this.eh());this.vb.set(e,m);this.Ca.push(m);return m}eh(){do this.wc++,65535<this.wc&&(this.wc=0);while(this.Tb.has(this.wc));const e=this.wc;this.Tb.add(e);return e}de(e){const m=e.H,c=e.U;this.b.j()&&!this.Ib&&this.nd.push(c);this.vb.delete(m);this.xc.delete(c);this.Tb.delete(c);e=this.Ca.indexOf(e);
-1<e&&this.Ca.splice(e,1)}xh(){this.nd.length=0;this.vb.clear();this.xc.clear();this.Tb.clear();this.Ca.length=0}me(e,m){this.yc=0;for(var c of this.Ca)c.Of(!1);for(let d=0,p=e.length;d<p;++d){c=e[d];const v=this.Oh(c.uid);v.Of(!0);v.me(c,m)}for(const d of this.Ca)d.wg||h.push(d);for(const d of h)this.de(d);h.length=0}oe(e,m,c){e.setUint16(m,this.U);m+=2;let d=0;this.Ib&&(d=1);e.setUint8(m,d);m+=1;e.setUint16(m,this.yc);m+=2;e.setUint16(m,this.Ma);m+=2;for(const p of this.Ca)p.Kd&&(m=p.oe(e,m,c));
return m}ri(e,m){if(this.vb.has(e))console.warn("OverrideNid passed id "+e+" which is already in use and cannot be overridden");else if(this.Tb.has(m))console.warn("OverrideNid passed nid "+m+" which is already in use and cannot be overridden");else{var c=new w(this,e,m);this.vb.set(e,c);this.Tb.add(m);this.Ca.push(c);this.Ib=!0}}ee(e){(e=this.vb.get(e))&&this.de(e)}fe(e){(e=this.xc.get(e))&&this.de(e)}Db(){return{hasOverriddenNids:this.Ib,netValues:this.xa.map(e=>e.Db()),netInstances:this.Ca.map(e=>
e.Db())}}Uh(){return{roId:this.Gc,sid:this.Hc,netValues:this.xa.map(e=>e.Db())}}}self.zf=g;self.sh=k;self.uh=n}"use strict";
{const h=self.sh,a=self.zf,b=window.RTCPeerConnection||window.webkitRTCPeerConnection||window.mozRTCPeerConnection||window.msRTCPeerConnection;function g(n){if(n)try{n.close()}catch(e){}}const k=[];class w{constructor(n,e,m){this.b=n;this.H=e;this.U=0;this.ea=m;this.rb=this.J=null;this.mc=!1;this.sb=null;this.oc=!1;this.tb=null;this.Re=this.Jc=this.ic=this.Hb=this.pc=!1;this.rd=this.sg=this.Ze=0;this.Fg=[];this.Cg=this.Bg=0;this.wa=[];this.L=this.C=this.Ea=null;this.zg=0;this.Je=!1;this.af=1;this.xd=
[];this.Ig=this.yd=0;this.b.Wi(this)}pb(n){this.U=n}j(){return this===this.b.P}Sc(){return this===this.b.O}Tk(){this.Bg=performance.now()}Uk(n){this.Cg=n}$c(n,e){n.binaryType="arraybuffer";n.onopen=()=>{"o"===e?this.mc=!0:"r"===e?this.oc=!0:"u"===e&&(this.pc=!0);this.yj()};n.onmessage=m=>{this.Tj(e,m)};n.onerror=m=>{console.error("Peer '"+this.H+"' datachannel '"+e+"' error: ",m);this.b.Ga(this,m);this.b.j()&&!this.j()&&this.S("network error")};n.onclose=()=>{this.S("disconnect")}}Bf(){if(!this.Sc()){var n=
this.b.j();this.ic=this.Hb=this.pc=this.oc=this.mc=!1;this.sg=performance.now();this.J=new b({iceServers:this.b.Ve});this.J.onicecandidate=m=>{m.candidate&&this.b.Fa({message:"icecandidate",toclientid:this.H,icecandidate:m.candidate})};this.J.onsignalingstatechange=()=>{this.J&&"closed"===this.J.signalingState&&this.S("disconnect")};this.J.oniceconnectionstatechange=()=>{this.J&&("failed"!==this.J.iceConnectionState&&"closed"!==this.J.iceConnectionState||this.S("disconnect"))};this.J.onconnectionstatechange=
()=>{if(this.J){var m=this.J.connectionState;"failed"!==m&&"closed"!==m||this.S("disconnect")}};var e=`c2mp_${this.b.Hh()}_${this.b.Ih()}_${this.b.Jh()}`;n?(this.U=this.b.vf(),this.rb=this.J.createDataChannel("o",{ordered:!0,protocol:e}),this.$c(this.rb,"o"),this.sb=this.J.createDataChannel("r",{ordered:!1,protocol:e}),this.$c(this.sb,"r"),this.tb=this.J.createDataChannel("u",{ordered:!1,maxRetransmits:0,protocol:e}),this.$c(this.tb,"u"),this.J.createOffer().then(m=>{this.J.setLocalDescription(m);
this.b.Fa({message:"offer",toclientid:this.H,offer:m})}).catch(m=>{console.error("Host error creating offer for peer '"+this.H+"': ",m);this.b.Ga(this,"could not create offer for peer")})):this.J.ondatachannel=m=>{if(m.channel.protocol!==e)console.error("Unexpected datachannel protocol '"+m.channel.protocol+"', should be '"+e+"'"),this.b.Ga(this,"unexpected datachannel protocol '"+m.channel.protocol+"', should be '"+e+"'");else{var c=m.channel.label;"o"===c?this.rb=m.channel:"r"===c?this.sb=m.channel:
"u"===c?this.tb=m.channel:(console.error("Unknown datachannel label: "+m.channel.label),this.b.Ga(this,"unknown datachannel label '"+m.channel.label+"'"));this.$c(m.channel,c)}}}}async Vi(n){if(this.J)try{await this.J.addIceCandidate(n)}catch(e){console.warn("[Multiplayer] Error adding ICE candidate: ",e)}}Wh(){return!!this.J}yj(){!this.Hb&&this.oc&&this.pc&&this.mc&&(this.Xj(),this.Hb=!0,this.ic=!1)}Xj(){this.Ze=performance.now();if(this.b.j()){this.b.Xb("o",JSON.stringify({c:"j",i:this.H,n:this.U,
a:this.ea}),this);this.$a("o",JSON.stringify({c:"hi",hn:this.b.P.U,n:this.U,d:this.b.Aa,u:this.b.Ac,objs:this.b.Th(),cvs:this.b.Gh()}));for(const n of this.b.Ia)!n.j()&&n!==this&&n.ae()&&this.$a("o",JSON.stringify({c:"j",i:n.H,n:n.U,a:n.ea}))}else this.Re=!0,this.j()&&this.he(performance.now(),!0);this.b.fg(this)}xj(n){!this.ic&&this.Hb&&(this.ye(n),this.ic=!0,this.Hb=!1)}ye(n){this.b.j()&&!this.Sc()&&this.b.Xb("o",JSON.stringify({c:"l",i:this.H,a:this.ea,r:n}),this);this.Sc()||this.b.eg(this,n)}ae(){return this.Hb&&
!this.ic}$a(n,e){this.b.Ri();var m=0;e.length?m=e.length:e.byteLength&&(m=e.byteLength);this.b.Pi(m);m=this.b.mf;const c=this.b.lf,d=this.b.nf;if(!(0<m&&"u"===n&&Math.random()<m))if(0===c&&0===d)this.Yf(n,e);else{let p=1;"u"!==n&&Math.random()<m&&(p=3);setTimeout(()=>this.Yf(n,e),c*p+Math.random()*d*p)}}Yf(n,e){try{"o"===n?this.mc&&this.rb&&this.rb.send(e):"r"===n?this.oc&&this.sb&&this.sb.send(e):"u"===n&&this.pc&&this.tb&&this.tb.send(e)}catch(m){this.Jc||(this.b.j()?"o"===n||"r"===n?("string"===
typeof e?(console.error("Error sending "+e.length+"-char string on '"+n+"' to '"+this.ea+"', host kicking: ",m),console.log("String that failed to send from previous error was: "+e)):console.error("Error sending "+(e.length||e.byteLength)+"-byte binary on '"+n+"' to '"+this.ea+"', host kicking: ",m),this.S("network error")):(this.rd++,10<=this.rd&&("string"===typeof e?(console.error("Too many errors ("+this.rd+") sending data on '"+n+"' to '"+this.ea+"', kicking; last error was for sending "+e.length+
"-char string: ",m),console.log("String that failed to send from previous error was: "+e)):console.error("Too many errors ("+this.rd+") sending data on '"+n+"' to '"+this.ea+"', kicking; last error was for sending "+(e.length||e.byteLength)+"-byte binary: ",m),this.S("network error"))):console.error("Error sending data on '"+n+"': ",m))}}he(n,e){this.Jc||(!e&&!this.ae()&&this.J&&25E3<n-this.sg?(console.warn("Timed out '"+this.ea+"', could not establish connection after 25sec"),this.S("timeout")):
!e&&this.ae()&&2E4<n-this.Ze?(console.warn("Timed out '"+this.ea+"', not heard from for 20sec"),this.S("timeout")):(this.zg=n,this.Je=!0,this.af++,this.$a("u","ping:"+this.af)))}wi(n){n="pong:"+n.substr(5);this.b.j()&&(n=n+"/"+Math.round(performance.now()).toString());this.$a("u",n)}ak(n){if(this.Je){var e=n.indexOf(":");if(-1<e){if(parseFloat(n.substr(e+1))===this.af){e=performance.now();this.Je=!1;var m=(e-this.zg)/2;this.xd.push(m);10<this.xd.length&&this.xd.shift();k.push(...this.xd);k.sort((v,
x)=>v-x);this.Ig=k[k.length-1]-k[0];var c=0,d=k.length;4<=k.length&&6>=k.length?(++c,--d):6<k.length&&(c+=2,d-=2);var p=0;for(let v=c;v<d;++v)p+=k[v];this.yd=p/(d-c);k.length=0;this.b.j()||(c=n.indexOf("/"),-1<c?(n=parseFloat(n.substr(c+1)),isFinite(n)?this.b.ah(n,e,m,this.yd):console.warn("Invalid host time from pong response")):console.warn("Cannot parse off host time from pong response"))}}else console.warn("Cannot parse off ping ID from pong")}}Tj(n,e){const m=this.b.mf,c=this.b.lf,d=this.b.nf;
if(!(0<m&&"u"===n&&Math.random()<m))if(0===c&&0===d)this.Xf(n,e);else{let p=1;"u"!==n&&Math.random()<m&&(p=3);setTimeout(()=>this.Xf(n,e),c*p+Math.random()*d*p)}}Xf(n,e){if(!this.Jc){this.Ze=performance.now();this.b.Qi();var m=0;e.data.length?m=e.data.length:e.data.byteLength&&(m=e.data.byteLength);this.b.Oi(m);if("string"===typeof e.data){if(!(""===e.data.trim()||4>e.data.length))if(n=e.data.substr(0,4),"ping"===n)this.wi(e.data);else if("pong"===n)this.ak(e.data);else{try{var c=JSON.parse(e.data)}catch(d){this.b.Ga(this,
d);this.b.j()?(console.error("Error parsing message as JSON for peer '"+this.H+"', host kicking: ",d),this.S("data error")):console.error("Error parsing message as JSON for peer '"+this.H+"': ",d);console.log("String that failed to parse from previous error: "+e.data);return}if(c)try{c.c&&"m"!==c.c?this.Dj(c):this.b.Yj(this,c)}catch(d){this.b.Ga(this,d),this.b.j()?(console.error("Error handling message for peer '"+this.H+"', host kicking: ",d),this.S("data error")):console.error("Error handling message for peer '"+
this.H+"': ",d)}}}else{!this.Re&&this.b.j()&&"u"===n&&(this.Re=!0,this.b.Ii(this.H));try{this.Cj(e.data)}catch(d){this.b.Ga(this,d),this.b.j()?(console.error("Error handling binary update for peer '"+this.H+"', host kicking: ",d),this.S("data error")):console.error("Error handling binary update for peer '"+this.H+"': ",d)}}}}Dj(n){switch(n.c){case "disconnect":n.k&&A(this.b,"peer-kicked");var e=!this.b.j()&&!this.j();this.S(n.r);e&&this.b.ke();break;case "hi":this.b.j()||(this.b.P.pb(n.hn),this.b.O.pb(n.n),
this.b.zi(n.d),this.b.Ei(n.u),this.b.hi(n.objs),this.b.gi(n.cvs));break;case "j":this.b.j()||(e=new w(this.b,n.i,n.a),e.pb(n.n),this.b.fg(e));break;case "l":!this.b.j()&&(e=this.b.Pc(n.i))&&(e.Sc()||this.b.eg(e,n.r),e.S(n.r));break;default:console.error("Unknown control message from peer '"+this.H+"': "+n.c),this.b.Ga(this,"unknown control message '"+n.c+"'")}}Cj(n){this.b.j()?this.Pj(n):this.Zj(n)}Pj(n){n=new DataView(n);let e=0;var m=n.getUint32(e);e+=4;if(1664249200!==m)console.warn("Rejected packet with incorrect magic number (received '"+
m+"', expected '1664249200'");else if(m=n.getFloat64(e),e+=8,m+=this.yd,!(3E3<=Math.abs(m-performance.now()))){n.getUint8(e);e+=1;var c=n.getUint8(e);e+=1;var d=[],p=this.b.Ha;for(let x=0;x<c;++x)if(x>=p.length)d.push(0);else{var v=p[x];switch(v.fb){case 0:v=n.getFloat64(e);e+=8;break;case 1:v=n.getFloat32(e);e+=4;break;case 2:v=v.Vc(n.getInt16(e));e+=2;break;case 3:v=v.Vc(n.getUint8(e));e+=1;break;default:v=n.getFloat32(e),e+=4}d.push(v)}this.Ui(m,d)}}Ui(n,e){for(let m=0,c=this.wa.length;m<c;++m){const d=
this.wa[m];if(d.timestamp===n)return;if(d.timestamp>n){this.wa.splice(m,0,new h(n,e));return}}this.wa.push(new h(n,e))}la(n){if(0!==this.wa.length){for(;2<this.wa.length&&this.wa[0]!==this.Ea&&this.wa[0]!==this.C&&this.wa[0]!==this.L;)this.wa.shift();if(!(this.L&&this.L.timestamp>n&&this.C&&this.C.timestamp<n)){this.L=null;for(let e=0,m=this.wa.length;e<m;++e){const c=this.wa[e];if(c.timestamp<=n){if(!this.C||c.timestamp>this.C.timestamp)this.Ea=this.C,this.C=c}else{this.L=c;break}}}}}Zj(n){n=new DataView(n);
let e=0;var m=n.getUint32(e);e+=4;1664249200!==m?console.warn("Rejected packet with incorrect magic number (received '"+m+"', expected '1664249200'"):(m=n.getUint32(e),e+=4,0===m?this.sj(n,e):1===m?this.rj(n,e):console.warn("Ignoring packet with incorrect flags (received "+m+", expected 0 or 1"))}sj(n,e){const m=n.getFloat64(e);e+=8;const c=n.getUint16(e);e+=2;for(let x=0;x<c;++x){var d=n.getUint16(e);e+=2;var p=n.getUint8(e);e+=1;let z=null,q=0;const r=this.b.Hf(d);r?(z=r.xa,q=z.length,1===p&&r.Rk()):
console.warn("Don't know which object corresponds to NID "+d);d=n.getUint16(e);e+=2;p=n.getUint16(e);e+=2;for(let f=0;f<d;++f){const l=n.getUint16(e);e+=2;if(r){const u=[];let t=e;for(let y=0;y<q;++y){var v=z[y];switch(v.fb){case 0:v=n.getFloat64(t);t+=8;break;case 1:v=n.getFloat32(t);t+=4;break;case 2:v=v.Vc(n.getInt16(t));t+=2;break;case 3:v=v.Vc(n.getUint8(t));t+=1;break;default:v=n.getFloat32(t),t+=4}u.push(v)}r.Qd(m,l,u)}e+=p}}}rj(n,e){const m=n.getFloat64(e);e+=8;const c=n.getUint16(e);e+=2;
for(let p=0;p<c;++p){var d=n.getUint16(e);e+=2;const v=this.b.Hf(d);v||console.warn("Don't know which object corresponds to NID "+d);d=n.getUint16(e);e+=2;for(let x=0;x<d;++x){const z=n.getUint16(e);e+=2;v&&!v.Ib&&(this.b.Qj(v,z,m),v.fe(z))}}}S(n,e){this.Jc||(this.Jc=!0,this.xj(n),this.$a("o",JSON.stringify({c:"disconnect",r:n,k:!!e})),g(this.rb),g(this.sb),g(this.tb),g(this.J),this.J=this.tb=this.sb=this.rb=null,this.pc=this.oc=this.mc=!1,this.b.Fk(this))}Mh(n){n=n.kc;if(!this.L&&!this.C)return 0;
if(this.L&&!this.C){var e=this.L.data;return 0>n||n>=e.length?0:e[n]}var m=this.b.Qc();let c,d;if(!this.L&&this.C){if(this.Ea){var p=this.Ea.timestamp;e=this.Ea.data[n];c=this.C.timestamp;d=this.C.data[n];m>this.C.timestamp+250&&(m=this.C.timestamp+250);p=p===c?0:(m-p)/(c-p);return a.Rc(this.b.Ha[n].Za(),e,d,p,!0)}e=this.C.data;return 0>n||n>=e.length?0:e[n]}p=this.C.timestamp;e=this.C.data[n];c=this.L.timestamp;d=this.L.data[n];p=p===c?0:(m-p)/(c-p);return a.Rc(this.b.Ha[n].Za(),e,d,p,!1)}}self.th=
w}"use strict";
{const h=self.zf,a=self.th,b=window.RTCPeerConnection||window.webkitRTCPeerConnection||window.mozRTCPeerConnection||window.msRTCPeerConnection,g=window.RTCSessionDescription||window.webkitRTCSessionDescription||window.mozRTCSessionDescription||window.msRTCSessionDescription,k=window.RTCIceCandidate||window.webkitRTCIceCandidate||window.mozRTCIceCandidate||window.msRTCIceCandidate,w=window.RTCDataChannel||window.webkitRTCDataChannel||window.mozRTCDataChannel||window.msRTCDataChannel,n=[{urls:"stun:stun.l.google.com:19302"}];
let e=!1;const m=[];self.kb.Ab(class extends self.Bb{constructor(c){super(c,"multiplayer");this.Ve=[];this.V=null;this.ta=this.Na=!1;this.tl={Yg:0,version:0,name:"",Ug:"",Tg:""};this.ma=this.Pe=this.Oe=this.ff=this.gf="";this.Ia=[];this.Ua=new Map;this.Mb=0;this.Ld=new Set;this.P=this.O=null;this.Aa=80;this.Ac=this.Ue=30;this.Eg=0;this.yb={Mc:0,Wg:0,sf:0,Vg:0,Pd:0,Sg:0,rf:0,Rg:0,Od:0};this.md=new ArrayBuffer(262144);this.Me=new DataView(this.md);this.za=[];this.ql=1;this.Dc=new Map;this.Ec=new Map;
this.mf=this.nf=this.lf=0;this.wb=[];this.da=this.Oa=0;this.na=this.Wa=this.Aa;this.Ha=[];this.ld=new Map;this.kf=!1;this.we(n);setInterval(()=>this.hj(),2E3);window.addEventListener("unload",()=>this.$b("quit"));E(this,"get-supported",()=>this.Mj());E(this,"add-ice-servers",d=>this.we(d.list));E(this,"simulate-latency",d=>this.Bi(d.latency,d.pdv,d.loss));E(this,"set-bandwidth-profile",d=>this.yi(d.updateRate,d.delay));E(this,"tick",d=>this.la(d));E(this,"alert",d=>this.dh(d));E(this,"signalling-connect",
d=>this.Ji(d.url));E(this,"signalling-disconnect",()=>this.Tf());E(this,"signalling-login",d=>this.Li(d.alias));E(this,"signalling-join-room",d=>this.Ki(d.game,d.instance,d.room,d.maxClients));E(this,"signalling-auto-join-room",d=>this.Hi(d.game,d.instance,d.room,d.maxClients,d.lock));E(this,"signalling-leave-room",()=>this.ke());E(this,"signalling-list-game-instances",d=>this.Mi(d.game));E(this,"signalling-list-rooms",d=>this.Ni(d.game,d.instance,d.which));E(this,"disconnect-room",()=>this.Ff(!0));
E(this,"peer-send-message",d=>this.li(d));E(this,"host-broadcast",d=>this.ji(d));E(this,"kick-peer",d=>this.ki(d));E(this,"sync-object",d=>this.pi(d));E(this,"sync-inst-var",d=>this.oi(d));E(this,"associate-object",d=>this.ii(d));E(this,"remove-object-id",d=>this.ee(d.uid));E(this,"remove-net-insts",d=>this.mi(d));E(this,"remove-object-nid",d=>this.ni(d));E(this,"set-client-state",d=>this.Pf(d.tag,d.value));E(this,"add-client-input-value",d=>this.Zg(d.tag,d.precision,d.interp))}nj(c){return c?"string"===
typeof c?c:"string"===typeof c.message?c.message:"string"===typeof c.details?c.details:"string"===typeof c.data?c.data:"string"===typeof c.type?c.type:"unknown error":"unknown error"}$d(){return this.Na&&this.ta}Yb(){return this.$d()&&this.ma}j(){return this.Yb()&&this.O&&this.P===this.O}Hh(){return this.$d()?this.Oe:""}Ih(){return this.$d()?this.Pe:""}Jh(){return this.Yb()?this.ma:""}Bi(c,d,p){this.lf=Math.max(c,0);this.nf=Math.max(d,0);this.mf=Math.max(p,0)}Mj(){return{isSupported:!(!b||!w)}}Ji(c){if(!this.V&&
!this.Na){try{this.V=new WebSocket(c,"c2multiplayer")}catch(d){this.V=null;this.ob(d);return}this.V.onopen=()=>{-1===this.V.protocol.indexOf("c2multiplayer")?(this.ob("server does not support 'c2multiplayer' protocol"),this.V.close(1002,"'c2multiplayer' protocol required"),this.V=null,this.Na=!1):this.Na=!0};this.V.onclose=()=>{this.ik();this.ta=this.Na=!1;this.V=null};this.V.onerror=d=>{console.error("Signalling server error: ",d);this.ob(d)};this.V.onmessage=d=>{this.jk(d)}}}Tf(){this.V&&this.Na&&
(this.V.close(),this.V=null,this.Na=!1)}jk(c){let d;try{d=JSON.parse(c.data)}catch(p){this.ob(p);return}switch(d.message){case "welcome":this.wk(d);break;case "login-ok":this.rk(d);break;case "join-ok":this.nk(d);break;case "leave-ok":this.qk();break;case "kicked":this.pk();break;case "peer-joined":this.tk(d);break;case "peer-quit":this.uk(d);break;case "icecandidate":this.lk(d);break;case "offer":this.sk(d);break;case "answer":this.kk(d);break;case "instance-list":this.mk(d);break;case "room-list":this.vk(d);
break;case "error":this.ob(d.details);break;default:this.ob("received unknown signalling message")}}Vh(c){for(const d of this.Ve)if(d.urls===c.urls)return!0;return!1}we(c){if(c)for(let d of c)"string"===typeof d&&(d={urls:d}),this.Vh(d)||(d.hasOwnProperty("url")||(d.url=d.urls),this.Ve.push(d))}ob(c){A(this,"signalling-error",{message:this.nj(c)})}ik(){A(this,"signalling-close")}wk(c){if(1>c.protocolrev||1<c.protocolrev)this.ob("signalling server protocol revision not supported"),this.Tf();else{this.gf=
c.clientid;var d=this.tl;d.Yg=c.protocolrev;d.version=c.version;d.name=c.name;d.Ug=c.operator;d.Tg=c.motd;this.we(c.ice_servers);A(this,"signalling-welcome",{myid:this.gf,sigservinfo:{protocolrev:d.Yg,version:d.version,name:d.name,operator:d.Ug,motd:d.Tg}})}}rk(c){this.ff=c.alias;this.ta=!0;A(this,"signalling-login-ok",{myalias:this.ff})}Rh(){return this.ql++}vf(){if(this.j()){do this.Mb++,65535<this.Mb&&(this.Mb=0);while(this.Ld.has(this.Mb));var c=this.Mb;this.Ld.add(c);return c}}Eh(c){this.j()&&
this.Ld.delete(c)}nk(c){this.$b("disconnect");this.Oe=c.game;this.Pe=c.instance;this.ma=c.room;this.O=new a(this,this.gf,this.ff);c.host?(this.P=this.O,this.Mb=0,this.Ld.clear(),this.P.pb(this.vf())):(this.da=this.Oa=this.wb.length=0,this.Aa=80,this.Ac=this.Ue=30,this.na=this.Wa=this.Aa,this.P=new a(this,c.hostid,c.hostalias),this.P.Bf());A(this,"signalling-join-ok",{isHost:!!c.host,hostId:this.P.H,hostAlias:this.P.ea,game:this.Oe,gameInstance:this.Pe,room:this.ma})}qk(){this.ma="";A(this,"signalling-leave-ok")}pk(){this.Ff();
this.ma="";A(this,"signalling-kicked")}tk(c){if(this.ta&&this.ma&&this.j()){var d=this.Ua.get(c.peerid);d&&d.S("rejoin");(new a(this,c.peerid,c.peeralias)).Bf()}}uk(c){if(this.ta&&this.ma&&this.j()){var d=this.Ua.get(c.id);d&&d.S(c.reason)}}lk(c){if(this.ta&&this.ma){var d=this.Ua.get(c.from);d&&d.Vi(new k(c.icecandidate))}}sk(c){if(this.ta&&this.ma&&!this.j()&&this.O&&this.P&&this.P.Wh()&&c.from===this.P.H){var d=this.P.J;d.setRemoteDescription(new g(c.offer)).then(()=>{d.createAnswer().then(p=>
{d.setLocalDescription(p);this.Fa({message:"answer",toclientid:this.P.H,answer:p})}).catch(p=>{console.error("Peer error creating answer: ",p);this.Ga(this.O,"could not create answer to host offer")})}).catch(p=>{console.error("Peer error setting remote description: ",p);this.Ga(this.O,"could not set remote description")})}}kk(c){if(this.ta&&this.ma&&this.j()){var d=this.Ua.get(c.from);d&&d.J.setRemoteDescription(new g(c.answer)).catch(p=>{console.error("Host error setting remote description: ",p)})}}mk(c){A(this,
"signalling-instance-list",{list:c.list})}vk(c){A(this,"signalling-room-list",{list:c.list})}Fa(c){this.V&&this.Na&&this.V.send(JSON.stringify(c))}Li(c){this.ta||this.Fa({message:"login",protocolrev:1,alias:c})}Ki(c,d,p,v){this.ta&&!this.ma&&this.Fa({message:"join",game:c,instance:d,room:p,max_clients:v})}Hi(c,d,p,v,x){this.ta&&!this.ma&&this.Fa({message:"auto-join",game:c,instance:d,room:p,max_clients:v,lock_when_full:x})}ke(){this.ta&&this.Fa({message:"leave"})}Ii(c){this.ta&&this.j()&&this.Fa({message:"confirm-peer",
id:c})}Mi(c){this.V&&this.Na&&this.Fa({message:"list-instances",game:c})}Ni(c,d,p){this.V&&this.Na&&this.Fa({message:"list-rooms",game:c,instance:d,which:p})}Ff(c){this.da=this.Oa=this.wb.length=0;this.$b("disconnect");for(const d of this.za)d.xh();c&&this.ke()}Wi(c){this.Ia.push(c);this.Ua.set(c.H,c);A(this,"add-peer",{id:c.H,alias:c.ea})}Fk(c){A(this,"remove-peer",{id:c.H});this.j()&&this.Eh(c.U);const d=this.Ia.indexOf(c);-1<d&&this.Ia.splice(d,1);this.Ua.delete(c.H);this.P===c&&(this.P=null,this.$b("host quit"));
this.O===c&&(this.O=null,this.ma="",this.$b("disconnect"))}$b(c){if(!e){for(e=!0;this.Ia.length;)this.Ia[0].S(c);e=!1}}Pc(c){return this.Ua.get(c)||null}Fh(c){return(c=this.Ua.get(c))?c.ea:""}ji(c){const d=c.fromId,p=c.tag,v=c.message;c=c.mode;const x=this.Pc(d);this.Xb(c,JSON.stringify({c:"m",t:p,f:d,m:v}),x)}Xb(c,d,p){if(this.j()){var v=this.Ia.slice(0);for(const x of v)x&&x!==this.O&&x!==p&&x.$a(c,d)}}hj(){const c=performance.now();if(this.j()){m.push(...this.Ia);for(const d of m)d&&d!==this.O&&
d.he(c,!1);m.length=0}else this.P&&this.P.he(c,!1)}bh(c){this.za.push(c);this.Ec.set(c.Gc,c);this.Dc.set(c.U,c)}Th(){const c={};for(const [d,p]of this.Dc.entries())c[p.Hc]={nid:d,nvs:p.Qh()};return c}hi(c){this.Dc.clear();for(const d of this.za)if(c.hasOwnProperty(d.Hc.toString())){const p=c[d.Hc.toString()];d.pb(p.nid);this.Dc.set(p.nid,d);d.Ci(p.nvs)}else console.warn("Could not map object SID '"+d.Hc+"' - host did not send NID for it"),d.pb(-1)}Hf(c){return this.Dc.get(c)||null}la(c){if(!this.Yb())return null;
c=c.dt;const d=performance.now();d-this.Eg>=1E3/(this.j()?this.Ue:this.Ac)-5&&(this.xi(d),this.Eg=d);const p=this.yb;1E3<=d-p.Mc&&(p.Wg=p.sf,p.Vg=p.Pd,p.Sg=p.rf,p.Rg=p.Od,p.sf=0,p.Pd=0,p.rf=0,p.Od=0,p.Mc+=1E3,500<d-p.Mc&&(p.Mc=d),A(this,"stats",{stats:{outboundPerSec:p.Wg,outboundBandwidthPerSec:p.Vg,inboundPerSec:p.Sg,inboundBandwidthPerSec:p.Rg}}));this.j()||(this.da<this.Oa?(this.da+=10*c,this.da>this.Oa&&(this.da=this.Oa)):this.da>this.Oa&&(this.da-=10*c,this.da<this.Oa&&(this.da=this.Oa)),this.na<
this.Wa?(this.na+=30*c,this.na>this.Wa&&(this.na=this.Wa)):this.na>this.Wa&&(this.na-=30*c,this.na<this.Wa&&(this.na=this.Wa)));c=this.Qc();for(const v of this.Ia)v.la(c);for(const v of this.za)v.la();return{simulationTime:this.Qc(),hostInputArrivalTime:this.Lh(),clientDelay:this.Aa,peerData:this.pj(),roData:this.qj(),isReadyForInput:this.Jf()}}pj(){const c={};for(const d of this.Ia){const p={};for(const v of this.Ha)p[v.$]=d.Mh(v);c[d.H]={nid:d.U,latency:d.yd,pdv:d.Ig,clientState:p}}return c}qj(){const c=
{};for(const d of this.za)c[d.Gc]=d.Db();return c}async xi(c){this.j()?(await this.Mk(c),this.Lk(c)):await this.Kk(c)}async Aj(){const c=await B(this,"before-client-update");for(const d of c.clientStateUpdates)this.Pf(d.tag,d.value)}async Kk(c){this.Jf()&&await this.Aj();if(this.O&&this.kf){var d=this.Me,p=0,v=this.Ha,x=this.O.Fg,z=c-this.O.Bg,q=c-this.O.Cg;if(100>z||(1E3>z?95<=q:495<=q)){d.setUint32(p,1664249200);p+=4;d.setFloat64(p,c+this.da);p+=8;d.setUint8(p,0);p+=1;d.setUint8(p,v.length);p+=
1;for(let r=0,f=v.length;r<f;++r)z=v[r],q=0,r<x.length&&(q=z.Af(x[r])),p=z.Uf(d,p,q);this.O.Uk(c);this.P.$a("u",new Uint8Array(this.md,0,p))}}}async Mk(c){const d=this.Me;let p=0,v=0;const x=await B(this,"get-object-info",{ros:this.za.map(z=>z.Uh())});for(const z of this.za){const q=z.Gc;x.hasOwnProperty(q)&&(z.me(x[q],c),0<z.yc&&v++)}if(0!==v){d.setUint32(p,1664249200);p+=4;d.setUint32(p,0);p+=4;d.setFloat64(p,c);p+=8;d.setUint16(p,v);p+=2;for(const z of this.za)0<z.yc&&(p=z.oe(d,p,c));this.Xb("u",
new Uint8Array(this.md,0,p),null)}}Lk(c){const d=this.Me;let p=0,v=0;for(const x of this.za)x.nd.length&&v++;if(0!==v){d.setUint32(p,1664249200);p+=4;d.setUint32(p,1);p+=4;d.setFloat64(p,c);p+=8;d.setUint16(p,v);p+=2;for(const x of this.za)if(c=x.nd,c.length){d.setUint16(p,x.U);p+=2;d.setUint16(p,c.length);p+=2;for(const z of c)d.setUint16(p,z),p+=2;c.length=0}this.Xb("r",new Uint8Array(this.md,0,p),null)}}ah(c,d,p,v){if(!this.j()){this.Wa=v+this.Aa;c=c+p-d;0===this.wb.length&&(this.da=c,this.na=
this.Wa);this.wb.push(c);30<this.wb.length&&this.wb.shift();m.push(...this.wb);m.sort((x,z)=>x-z);c=0;d=m.length;4<=m.length&&6>=m.length?(++c,--d):6<m.length&&19>=m.length?(c+=2,d-=2):19<m.length&&(c+=5,d-=5);p=0;for(v=c;v<d;++v)p+=m[v];this.Oa=p/(d-c);m.length=0}}Qc(){return this.j()?performance.now()-this.Aa:performance.now()+this.da-this.na}Lh(){return this.j()?performance.now():performance.now()+this.da+this.na}Pf(c,d){if(!this.j()&&this.O&&this.kf&&(c=this.ld.get(c))){c=c.kc;var p=this.O.Fg;
p.length<c+1&&(p.length=c+1);p[c]!==d&&(p[c]=d,this.O.Tk())}}Zg(c,d,p){d=new h(this.Ha.length,p,d,c,null);this.ld.set(c,d);this.Ha.push(d)}Gh(){const c=[];for(const d of this.Ha)c.push({tag:d.$,precision:d.fb,interp:d.Za()});return c}gi(c){this.ld.clear();this.Ha.length=0;for(let p=0,v=c.length;p<v;++p){var d=c[p];d=new h(p,d.interp,d.precision,d.tag,null);this.ld.set(d.$,d);this.Ha.push(d)}this.kf=!0}ee(c){for(const d of this.za)d.ee(c)}Jf(){return this.Yb()?this.j()?!0:0!==this.Oa:!1}yi(c,d){this.Yb()||
(this.Ac=this.Ue=c,this.Aa=d)}fg(c){A(this,"peer-open",{id:c.H,alias:c.ea})}li(c){const d=c.tag,p=c.message,v=c.mode;(c=this.Pc(c.id))&&c.$a(v,JSON.stringify({c:"m",t:d,m:p}))}eg(c,d){A(this,"peer-close",{id:c.H,alias:c.ea,reason:d||"unknown"})}Ga(c,d){console.error(`[Multiplayer] Peer '${c.ea}' (${c.H}) error: `,d)}Yj(c,d){c=d.f||c.H;A(this,"peer-message",{tag:d.t,fromId:c,fromAlias:this.Fh(c),content:d.m})}Qj(c,d,p){A(this,"instance-destroyed",{roId:c.Gc,nid:d,timestamp:p})}ki(c){if(this.j()){var d=
c.reason;(c=this.Pc(c.id))&&c.S(d,!0)}}Ri(){this.yb.sf++}Pi(c){this.yb.Pd+=c}Qi(){this.yb.rf++}Oi(c){this.yb.Od+=c}zi(c){this.Aa=c}Ei(c){this.Ac=c}pi(c){const d=c.data,p=c.precision,v=c.bandwidth;for(const x of c.objectClasses)c=new self.uh(this,x.roId,x.sid,v),1===d?(c.Ya(1,p,"x"),c.Ya(1,p,"y")):2===d?c.Ya(2,p,"a"):3===d&&(c.Ya(1,p,"x"),c.Ya(1,p,"y"),c.Ya(2,p,"a"))}dh(c){alert(c.message)}oi(c){const d=c.precision,p=c.interp,v=c.cvt;for(const x of c.syncData)this.Ec.get(x.roId).Ya(p,d,"iv",x.varIndex,
v)}ii(c){var d=c.peerId;const p=c.instUid;c=this.Ec.get(c.roId);d=this.Ua.get(d);c&&d&&this.j()&&c.ri(p,d.U)}mi(c){for(const [d,p]of Object.entries(c))if(c=this.Ec.get(parseInt(d,10)))for(const v of p)c.fe(v)}ni(c){const d=c.nid;(c=this.Ec.get(c.roId))&&c.fe(d)}})}"use strict";function Q(h){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>A(h,"sw-message",a.data))}
function R(h){h=h.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(h).catch(a=>console.warn("[Construct 3] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(h):screen.webkitLockOrientation?a=screen.webkitLockOrientation(h):screen.mozLockOrientation?a=screen.mozLockOrientation(h):screen.msLockOrientation&&(a=screen.msLockOrientation(h));a||console.warn("[Construct 3] Failed to lock orientation")}catch(a){console.warn("[Construct 3] Failed to lock orientation: ",
a)}}
self.kb.Ab(class extends self.Bb{constructor(h){super(h,"browser");this.T="";F(this,[["get-initial-state",a=>{this.T=a.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isScirraArcade:"undefined"!==typeof window.is_scirra_arcade}}],["ready-for-sw-messages",()=>Q(this)],
["alert",a=>this.xe(a)],["close",()=>this.ye()],["set-focus",a=>this.Ee(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>R(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],
["navigate",a=>{var b=a.type;if("back"===b)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.back();else if("forward"===b)window.forward();else if("home"===b)window.home();else if("reload"===b)location.reload();else if("url"===b){b=a.url;var g=a.target;a=a.exportType;"windows-uwp"===a&&"undefined"!==typeof Windows?Windows.System.Launcher.launchUriAsync(new Windows.Foundation.Uri(b)):self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):"preview"===
a?window.open(b,"_blank"):this.Il||(2===g?window.top.location=b:1===g?window.parent.location=b:window.location=b)}else"new-window"===b&&(b=a.url,g=a.tag,"windows-uwp"===a.exportType&&"undefined"!==typeof Windows?Windows.System.Launcher.launchUriAsync(new Windows.Foundation.Uri(b)):self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):window.open(b,g))}],["request-fullscreen",a=>{{const b={navigationUI:"auto"};a=a.navUI;1===a?b.navigationUI="hide":2===a&&(b.navigationUI=
"show");a=document.documentElement;a.requestFullscreen?a.requestFullscreen(b):a.mozRequestFullScreen?a.mozRequestFullScreen(b):a.msRequestFullscreen?a.msRequestFullscreen(b):a.webkitRequestFullScreen&&("undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen())}}],["exit-fullscreen",()=>{document.exitFullscreen?document.exitFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():document.msExitFullscreen?document.msExitFullscreen():
document.webkitCancelFullScreen&&document.webkitCancelFullScreen()}],["set-hash",a=>{location.hash=a.hash}]]);window.addEventListener("online",()=>{A(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{A(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{A(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",()=>{A(this,"backbutton")});"undefined"!==typeof Windows&&Windows.UI.Core.SystemNavigationManager.getForCurrentView().addEventListener("backrequested",
a=>{a.handled=!0;A(this,"backbutton")})}xe(h){alert(h.message)}ye(){navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}Ee(h){h=h.isFocus;if("nwjs"===this.T){const a="nwjs"===this.T?nw.Window.get():null;h?a.focus():a.blur()}else h?window.focus():window.blur()}});"use strict";async function S(h,a){a=a.type;let b=!0;0===a?b=await T():1===a&&(b=await U());A(h,"permission-result",{type:a,result:b})}
async function T(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(h){return console.warn("[Touch] Failed to request orientation permission: ",h),!1}}
async function U(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(h){return console.warn("[Touch] Failed to request motion permission: ",h),!1}}self.kb.Ab(class extends self.Bb{constructor(h){super(h,"touch");E(this,"request-permission",a=>S(this,a))}});"use strict";
{const h=180/Math.PI;self.Pa=class extends self.Bb{constructor(a){super(a,"audio");this.pd=this.o=null;this.td=this.Te=!1;this.gb=()=>this.hl();this.Ka=[];this.W=[];this.Sa=null;this.Ag="";this.Dg=-1;this.Bc=new Map;this.cf=1;this.bb=!1;this.qf=0;this.Jd=1;this.Qe=0;this.Hg="HRTF";this.tg="inverse";this.Jg=600;this.Gg=1E4;this.Lg=1;this.vg=this.jf=!1;this.ul=this.M.$h();this.La=new Map;this.Gb=new Set;this.Xe=!1;this.df="";this.xb=null;self.C3Audio_OnMicrophoneStream=(b,g)=>this.Vj(b,g);this.od=null;
self.C3Audio_GetOutputStream=()=>this.Lj();self.C3Audio_DOMInterface=this;F(this,[["create-audio-context",b=>this.ej(b)],["play",b=>this.Bk(b)],["stop",b=>this.el(b)],["stop-all",()=>this.fl()],["set-paused",b=>this.Yk(b)],["set-volume",b=>this.cl(b)],["fade-volume",b=>this.kj(b)],["set-master-volume",b=>this.Wk(b)],["set-muted",b=>this.Xk(b)],["set-silent",b=>this.$k(b)],["set-looping",b=>this.Vk(b)],["set-playback-rate",b=>this.Zk(b)],["seek",b=>this.Jk(b)],["preload",b=>this.Ck(b)],["unload",b=>
this.il(b)],["unload-all",()=>this.jl()],["set-suspended",b=>this.al(b)],["add-effect",b=>this.Vf(b)],["set-effect-param",b=>this.Pk(b)],["remove-effects",b=>this.Ek(b)],["tick",b=>this.xk(b)],["load-state",b=>this.Sj(b)]])}async ej(a){a.isiOSCordova&&(this.jf=!0);this.qf=a.timeScaleMode;this.Hg=["equalpower","HRTF","soundfield"][a.panningModel];this.tg=["linear","inverse","exponential"][a.distanceModel];this.Jg=a.refDistance;this.Gg=a.maxDistance;this.Lg=a.rolloffFactor;var b={latencyHint:a.latencyHint};
if("undefined"!==typeof AudioContext)this.o=new AudioContext(b);else if("undefined"!==typeof webkitAudioContext)this.o=new webkitAudioContext(b);else throw Error("Web Audio API not supported");this.Wf();this.o.onstatechange=()=>{"running"!==this.o.state&&this.Wf()};this.pd=this.o.createGain();this.pd.connect(this.o.destination);b=a.listenerPos;this.o.listener.setPosition(b[0],b[1],b[2]);this.o.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=()=>this.Ud();try{await Promise.all(a.preloadList.map(g=>
this.ad(g.originalUrl,g.url,g.type,!1)))}catch(g){console.error("[Construct 3] Preloading sounds failed: ",g)}return{sampleRate:this.o.sampleRate}}Wf(){this.td||(this.Te=!1,window.addEventListener("pointerup",this.gb,!0),window.addEventListener("touchend",this.gb,!0),window.addEventListener("click",this.gb,!0),window.addEventListener("keydown",this.gb,!0),this.td=!0)}gj(){this.td&&(this.Te=!0,window.removeEventListener("pointerup",this.gb,!0),window.removeEventListener("touchend",this.gb,!0),window.removeEventListener("click",
this.gb,!0),window.removeEventListener("keydown",this.gb,!0),this.td=!1)}hl(){if(!this.Te){var a=this.o;"suspended"===a.state&&a.resume&&a.resume();var b=a.createBuffer(1,220,22050),g=a.createBufferSource();g.buffer=b;g.connect(a.destination);g.start(0);"running"===a.state&&this.gj()}}va(){return this.o}Ud(){return this.o.currentTime}ib(){return this.pd}Gf(a){return(a=this.La.get(a.toLowerCase()))?a[0].ka():this.ib()}$g(a,b){a=a.toLowerCase();let g=this.La.get(a);g||(g=[],this.La.set(a,g));b.Sk(g.length);
b.bl(a);g.push(b);this.jg(a)}jg(a){let b=this.ib();const g=this.La.get(a);if(g&&g.length){b=g[0].ka();for(let k=0,w=g.length;k<w;++k){const n=g[k];k+1===w?n.pa(this.ib()):n.pa(g[k+1].ka())}}for(const k of this.Xa(a))k.ti(b);this.xb&&this.df===a&&(this.xb.disconnect(),this.xb.connect(b))}Oc(){return this.cf}Tc(){return this.bb}Qk(){this.vg=!0}Bh(a,b){return b?this.M.kl(a).then(g=>{const k=this.o.createBuffer(1,g.length,48E3);k.getChannelData(0).set(g);return k}):new Promise((g,k)=>{this.o.decodeAudioData(a,
g,k)})}lb(a){this.M.lb(a)}Eb(a){this.M.Eb(a)}Nf(a){let b=0;for(let g=0,k=this.W.length;g<k;++g){const w=this.W[g];this.W[b]=w;w.ga===a?w.l():++b}this.W.length=b}vi(){let a=0;for(let b=0,g=this.Ka.length;b<g;++b){const k=this.Ka[b];this.Ka[a]=k;k.jb()?k.l():++a}this.Ka.length=a}*Xa(a){if(a)for(const b of this.W)self.Pa.Ch(b.$,a)&&(yield b);else this.Sa&&!this.Sa.qa()&&(yield this.Sa)}async ad(a,b,g,k,w){for(const n of this.Ka)if(n.Wb()===b)return await V(n),n;if(w)return null;k&&(this.jf||this.vg)&&
this.vi();w="audio/webm; codecs=opus"===g&&!this.ul;k&&w&&this.Qk();a=!k||this.jf||w?new self.vh(this,a,b,g,k,w):new self.qh(this,a,b,g,k);this.Ka.push(a);await V(a);return a}async re(a,b,g,k,w){for(const n of this.W)if(n.Wb()===b&&(n.Rd()||w))return n.Fi(k),n;a=await this.ad(a,b,g,w);k="html5"===a.Ie?new self.rh(a.A,a,k):new self.wh(a.A,a,k);this.W.push(k);return k}Xi(a){let b=this.Bc.get(a);if(!b){let g=null;b={tf:0,promise:new Promise(k=>g=k),resolve:g};this.Bc.set(a,b)}b.tf++}Gk(a){const b=this.Bc.get(a);
if(!b)throw Error("expected pending tag");b.tf--;0===b.tf&&(b.resolve(),this.Bc.delete(a))}le(a){a||(a=this.Ag);return(a=this.Bc.get(a))?a.promise:Promise.resolve()}bd(){if(0<this.Gb.size)G(this);else for(const a of this.W)if(a.If()){G(this);break}}la(){for(var a of this.Gb)a.la();a=this.Ud();for(var b of this.W)b.la(a);b=this.W.filter(g=>g.If()).map(g=>g.Vb());A(this,"state",{tickCount:this.Dg,audioInstances:b,analysers:[...this.Gb].map(g=>g.Kh())});0===b.length&&0===this.Gb.size&&this.ud&&(this.M.Hk(this.Og),
this.ud=!1)}ce(a,b,g){A(this,"trigger",{type:a,tag:b,aiid:g})}async Bk(a){const b=a.originalUrl,g=a.url,k=a.type,w=a.isMusic,n=a.tag,e=a.isLooping,m=a.vol,c=a.pos,d=a.panning;let p=a.off;0<p&&!a.trueClock&&(this.o.getOutputTimestamp?(a=this.o.getOutputTimestamp(),p=p-a.performanceTime/1E3+a.contextTime):p=p-performance.now()/1E3+this.o.currentTime);this.Ag=n;this.Xi(n);try{this.Sa=await this.re(b,g,k,n,w),d?(this.Sa.Xc(!0),this.Sa.Di(d.x,d.y,d.angle,d.innerAngle,d.outerAngle,d.outerGain),d.hasOwnProperty("uid")&&
this.Sa.Gi(d.uid)):this.Sa.Xc(!1),this.Sa.Play(e,m,c,p)}catch(v){console.error("[Construct 3] Audio: error starting playback: ",v);return}finally{this.Gk(n)}G(this)}el(a){a=a.tag;for(const b of this.Xa(a))b.ab()}fl(){for(const a of this.W)a.ab()}Yk(a){const b=a.tag;a=a.paused;for(const g of this.Xa(b))a?g.Zb():g.Wc();this.bd()}cl(a){const b=a.tag;a=a.vol;for(const g of this.Xa(b))g.Zc(a)}async kj(a){const b=a.tag,g=a.vol,k=a.duration;a=a.stopOnEnd;await this.le(b);for(const w of this.Xa(b))w.Dh(g,
k,a);this.bd()}Wk(a){this.cf=a.vol;for(const b of this.W)b.hd()}Xk(a){const b=a.tag;a=a.isMuted;for(const g of this.Xa(b))g.Qf(a)}$k(a){this.bb=a.isSilent;this.M.Yc(this.bb);for(const b of this.W)b.gd()}Vk(a){const b=a.tag;a=a.isLooping;for(const g of this.Xa(b))g.ie(a)}async Zk(a){const b=a.tag;a=a.rate;await this.le(b);for(const g of this.Xa(b))g.Sf(a)}async Jk(a){const b=a.tag;a=a.pos;await this.le(b);for(const g of this.Xa(b))g.ge(a)}async Ck(a){const b=a.originalUrl,g=a.url,k=a.type;a=a.isMusic;
try{await this.re(b,g,k,"",a)}catch(w){console.error("[Construct 3] Audio: error preloading: ",w)}}async il(a){if(a=await this.ad("",a.url,a.type,a.isMusic,!0))a.l(),a=this.Ka.indexOf(a),-1!==a&&this.Ka.splice(a,1)}jl(){for(const a of this.Ka)a.l();this.Ka.length=0}al(a){a=a.isSuspended;!a&&this.o.resume&&this.o.resume();for(const b of this.W)b.je(a);a&&this.o.suspend&&this.o.suspend()}xk(a){this.Jd=a.timeScale;this.Qe=a.gameTime;this.Dg=a.tickCount;if(0!==this.qf)for(var b of this.W)b.Fb();(b=a.listenerPos)&&
this.o.listener.setPosition(b[0],b[1],b[2]);for(const g of a.instPans){a=g.uid;for(const k of this.W)k.Ra===a&&k.Rf(g.x,g.y,g.angle)}}async Vf(a){var b=a.type;const g=a.tag;var k=a.params;if("filter"===b)k=new self.kh(this,...k);else if("delay"===b)k=new self.ih(this,...k);else if("convolution"===b){b=null;try{b=await this.ad(a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(w){console.log("[Construct 3] Audio: error loading convolution: ",w);return}k=new self.hh(this,b.Ja,...k);k.Nk(a.bufferOriginalUrl,
a.bufferType)}else if("flanger"===b)k=new self.lh(this,...k);else if("phaser"===b)k=new self.nh(this,...k);else if("gain"===b)k=new self.mh(this,...k);else if("tremolo"===b)k=new self.ph(this,...k);else if("ringmod"===b)k=new self.oh(this,...k);else if("distortion"===b)k=new self.jh(this,...k);else if("compressor"===b)k=new self.gh(this,...k);else if("analyser"===b)k=new self.fh(this,...k);else throw Error("invalid effect type");this.$g(g,k);this.ig()}Pk(a){const b=a.index,g=a.param,k=a.value,w=a.ramp,
n=a.time;a=this.La.get(a.tag);!a||0>b||b>=a.length||(a[b].ya(g,k,w,n),this.ig())}Ek(a){a=a.tag.toLowerCase();const b=this.La.get(a);if(b&&b.length){for(const g of b)g.l();this.La.delete(a);this.jg(a)}}Ti(a){this.Gb.add(a);this.bd()}Dk(a){this.Gb.delete(a)}ig(){this.Xe||(this.Xe=!0,Promise.resolve().then(()=>this.ij()))}ij(){const a={};for(const [b,g]of this.La)a[b]=g.map(k=>k.Vb());A(this,"fxstate",{fxstate:a});this.Xe=!1}async Sj(a){const b=a.saveLoadMode;if(3!==b)for(var g of this.W)g.jb()&&1===
b||(g.jb()||2!==b)&&g.ab();for(const k of this.La.values())for(const w of k)w.l();this.La.clear();this.Jd=a.timeScale;this.Qe=a.gameTime;g=a.listenerPos;this.o.listener.setPosition(g[0],g[1],g[2]);this.bb=a.isSilent;this.M.Yc(this.bb);this.cf=a.masterVolume;g=[];for(const k of Object.values(a.effects))g.push(Promise.all(k.map(w=>this.Vf(w))));await Promise.all(g);await Promise.all(a.playing.map(k=>this.wj(k,b)));this.bd()}async wj(a,b){if(3!==b){var g=a.bufferOriginalUrl,k=a.bufferUrl,w=a.bufferType,
n=a.isMusic,e=a.tag,m=a.isLooping,c=a.volume,d=a.playbackTime;if(!n||1!==b)if(n||2!==b){b=null;try{b=await this.re(g,k,w,e,n)}catch(p){console.error("[Construct 3] Audio: error loading audio state: ",p);return}b.fi(a.pan);b.Play(m,c,d,0);a.isPlaying||b.Zb();b.ve(a)}}}Vj(a,b){this.xb&&this.xb.disconnect();this.df=b.toLowerCase();this.xb=this.o.createMediaStreamSource(a);this.xb.connect(this.Gf(this.df))}Lj(){this.od||(this.od=this.o.createMediaStreamDestination(),this.pd.connect(this.od));return this.od.stream}static Ch(a,
b){return a.length!==b.length?!1:a===b?!0:a.toLowerCase()===b.toLowerCase()}static Si(a){return a*h}static Ah(a){return Math.pow(10,a/20)}static Ef(a){return Math.max(Math.min(self.Pa.Ah(a),1),0)}static ei(a){return Math.log(a)/Math.log(10)*20}static di(a){return self.Pa.ei(Math.max(Math.min(a,1),0))}static wl(a,b){return 1-Math.exp(-b*a)}};self.kb.Ab(self.Pa)}"use strict";function V(h){h.zd||(h.zd=h.ue());return h.zd}
self.xf=class{constructor(h,a,b,g,k){this.A=h;this.rl=a;this.zb=b;this.oa=g;this.nl=k;this.Ie="";this.zd=null}l(){this.zd=this.A=null}ue(){}va(){return this.A.va()}Wd(){return this.rl}Wb(){return this.zb}Vd(){return this.oa}jb(){return this.nl}Qa(){}};"use strict";
self.qh=class extends self.xf{constructor(h,a,b,g,k){super(h,a,b,g,k);this.Ie="html5";this.ba=new Audio;this.ba.crossOrigin="anonymous";this.ba.autoplay=!1;this.ba.preload="auto";this.rc=this.sc=null;this.ba.addEventListener("canplaythrough",()=>!0);this.zc=this.va().createGain();this.uc=null;this.ba.addEventListener("canplay",()=>{this.sc&&(this.sc(),this.rc=this.sc=null);!this.uc&&this.ba&&(this.uc=this.va().createMediaElementSource(this.ba),this.uc.connect(this.zc))});this.onended=null;this.ba.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.ba.addEventListener("error",w=>{console.error(`[Construct 3] Audio '${this.zb}' error: `,w);this.rc&&(this.rc(w),this.rc=this.sc=null)})}l(){this.A.Nf(this);this.zc.disconnect();this.zc=null;this.uc.disconnect();this.uc=null;this.ba&&!this.ba.paused&&this.ba.pause();this.ba=this.onended=null;super.l()}ue(){return new Promise((h,a)=>{this.sc=h;this.rc=a;this.ba.src=this.zb})}ja(){return this.ba}Qa(){return this.ba.duration}};"use strict";
async function W(h){if(h.qb)return h.qb;var a=h.A.M;if("cordova"===a.T&&a.ai(h.zb)&&"file:"===location.protocol)h.qb=await a.Sd(h.zb);else{a=await fetch(h.zb);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);h.qb=await a.arrayBuffer()}}async function X(h){if(h.Ja)return h.Ja;h.Ja=await h.A.Bh(h.qb,h.pl);h.qb=null}
self.vh=class extends self.xf{constructor(h,a,b,g,k,w){super(h,a,b,g,k);this.Ie="webaudio";this.Ja=this.qb=null;this.pl=!!w}l(){this.A.Nf(this);this.Ja=this.qb=null;super.l()}async ue(){try{await W(this),await X(this)}catch(h){console.error(`[Construct 3] Failed to load audio '${this.zb}': `,h)}}Qa(){return this.Ja?this.Ja.duration:0}};"use strict";
{let h=0;self.yf=class{constructor(a,b,g){this.A=a;this.ga=b;this.$=g;this.jd=h++;this.ha=this.va().createGain();this.ha.connect(this.ib());this.N=null;this.nc=!1;this.Y=!0;this.sa=this.Va=this.X=!1;this.Ic=1;this.Jb=!1;this.Da=1;a=this.A.qf;this.Ye=1===a&&!this.jb()||2===a;this.fc=this.Ra=-1;this.Ng=!1}l(){this.ga=this.A=null;this.N&&(this.N.disconnect(),this.N=null);this.ha.disconnect();this.ha=null}va(){return this.A.va()}ib(){return this.A.Gf(this.$)}Oc(){return this.A.Oc()}Nc(){return this.Ye?
this.A.Qe:performance.now()/1E3}Wd(){return this.ga.Wd()}Wb(){return this.ga.Wb()}Vd(){return this.ga.Vd()}jb(){return this.ga.jb()}Fi(a){this.$=a}qa(){}Rd(){}IsPlaying(){return!this.Y&&!this.X&&!this.qa()}If(){return!this.Y&&!this.qa()}Cb(){}Qa(){return this.ga.Qa()}Play(){}ab(){}Zb(){}Wc(){}Zc(a){this.Ic=a;this.ha.gain.cancelScheduledValues(0);this.fc=-1;this.ha.gain.value=this.Xd()}Dh(a,b,g){if(!this.Jb){a*=this.Oc();var k=this.ha.gain;k.cancelScheduledValues(0);var w=this.A.Ud();b=w+b;k.setValueAtTime(k.value,
w);k.linearRampToValueAtTime(a,b);this.Ic=a;this.fc=b;this.Ng=g}}hd(){this.Zc(this.Ic)}la(a){-1!==this.fc&&a>=this.fc&&(this.fc=-1,this.Ng&&this.ab(),this.A.ce("fade-ended",this.$,this.jd))}Xd(){const a=this.Ic*this.Oc();return isFinite(a)?a:0}Qf(a){a=!!a;this.Jb!==a&&(this.Jb=a,this.gd())}Tc(){return this.A.Tc()}gd(){}ie(){}Sf(a){this.Da!==a&&(this.Da=a,this.Fb())}Fb(){}ge(){}je(){}Xc(a){a=!!a;this.nc!==a&&((this.nc=a)?(this.N||(this.N=this.va().createPanner(),this.N.panningModel=this.A.Hg,this.N.distanceModel=
this.A.tg,this.N.refDistance=this.A.Jg,this.N.maxDistance=this.A.Gg,this.N.rolloffFactor=this.A.Lg),this.ha.disconnect(),this.ha.connect(this.N),this.N.connect(this.ib())):(this.N.disconnect(),this.ha.disconnect(),this.ha.connect(this.ib())))}Di(a,b,g,k,w,n){this.nc&&(this.Rf(a,b,g),a=self.Pa.Si,this.N.coneInnerAngle=a(k),this.N.coneOuterAngle=a(w),this.N.coneOuterGain=n)}Rf(a,b,g){this.nc&&(this.N.setPosition(a,b,0),this.N.setOrientation(Math.cos(g),Math.sin(g),0))}Gi(a){this.Ra=a}Yd(){}ti(a){const b=
this.N||this.ha;b.disconnect();b.connect(a)}Vb(){return{aiid:this.jd,tag:this.$,duration:this.Qa(),volume:this.Ic,isPlaying:this.IsPlaying(),playbackTime:this.Cb(),playbackRate:this.Da,uid:this.Ra,bufferOriginalUrl:this.Wd(),bufferUrl:"",bufferType:this.Vd(),isMusic:this.jb(),isLooping:this.sa,isMuted:this.Jb,resumePosition:this.Yd(),pan:this.Sh()}}ve(a){this.Sf(a.playbackRate);this.Qf(a.isMuted)}Sh(){if(!this.N)return null;const a=this.N;return{pos:[a.positionX.value,a.positionY.value,a.positionZ.value],
orient:[a.orientationX.value,a.orientationY.value,a.orientationZ.value],cia:a.coneInnerAngle,coa:a.coneOuterAngle,cog:a.coneOuterGain,uid:this.Ra}}fi(a){a?(this.Xc(!0),a=this.N,a.setPosition(...a.pos),a.setOrientation(...a.orient),a.coneInnerAngle=a.cia,a.coneOuterAngle=a.coa,a.coneOuterGain=a.cog,this.Ra=a.uid):this.Xc(!1)}}}"use strict";
self.rh=class extends self.yf{constructor(h,a,b){super(h,a,b);this.ga.zc.connect(this.ha);this.ga.onended=()=>this.ze()}l(){this.ab();this.ga.zc.disconnect();super.l()}ja(){return this.ga.ja()}ze(){this.Y=!0;this.Ra=-1;this.A.ce("ended",this.$,this.jd)}qa(){return this.ja().ended}Rd(){return this.Y?!0:this.qa()}Cb(h){let a=this.ja().currentTime;h&&(a*=this.Da);this.sa||(a=Math.min(a,this.Qa()));return a}Play(h,a,b){const g=this.ja();1!==g.playbackRate&&(g.playbackRate=1);g.loop!==h&&(g.loop=h);this.Zc(a);
g.muted&&(g.muted=!1);if(g.currentTime!==b)try{g.currentTime=b}catch(k){console.warn(`[Construct 3] Exception seeking audio '${this.ga.Wb()}' to position '${b}': `,k)}this.A.lb(g);this.X=this.Y=!1;this.sa=h;this.Da=1}ab(){const h=this.ja();h.paused||h.pause();this.A.Eb(h);this.Y=!0;this.X=!1;this.Ra=-1}Zb(){if(!(this.X||this.Y||this.qa())){var h=this.ja();h.paused||h.pause();this.A.Eb(h);this.X=!0}}Wc(){!this.X||this.Y||this.qa()||(this.A.lb(this.ja()),this.X=!1)}gd(){this.ja().muted=this.Jb||this.Tc()}ie(h){h=
!!h;this.sa!==h&&(this.sa=h,this.ja().loop=h)}Fb(){let h=this.Da;this.Ye&&(h*=this.A.Jd);try{this.ja().playbackRate=h}catch(a){console.warn(`[Construct 3] Unable to set playback rate '${h}':`,a)}}ge(h){if(!this.Y&&!this.qa())try{this.ja().currentTime=h}catch(a){console.warn(`[Construct 3] Error seeking audio to '${h}': `,a)}}Yd(){return this.Cb()}je(h){h?this.IsPlaying()?(this.ja().pause(),this.Va=!0):this.Va=!1:this.Va&&(this.A.lb(this.ja()),this.Va=!1)}};"use strict";
function Y(h){h.B&&h.B.disconnect();h.B=null;h.bc=null}
self.wh=class extends self.yf{constructor(h,a,b){super(h,a,b);this.B=null;this.Cd=g=>this.ze(g);this.Se=!0;this.bc=null;this.ia=this.Id=0;this.ef=1}l(){this.ab();Y(this);this.Cd=null;super.l()}ze(h){this.X||this.Va||h.target!==this.bc||(this.Y=this.Se=!0,this.Ra=-1,Y(this),this.A.ce("ended",this.$,this.jd))}qa(){return!this.Y&&this.B&&this.B.loop||this.X?!1:this.Se}Rd(){return!this.B||this.Y?!0:this.qa()}Cb(h){let a;a=this.X?this.ia:this.Nc()-this.Id;h&&(a*=this.Da);this.sa||(a=Math.min(a,this.Qa()));
return a}Play(h,a,b,g){this.ef=1;this.Zc(a);Y(this);this.B=this.va().createBufferSource();this.B.buffer=this.ga.Ja;this.B.connect(this.ha);this.bc=this.B;this.B.onended=this.Cd;this.B.loop=h;this.B.start(g,b);this.X=this.Y=this.Se=!1;this.sa=h;this.Da=1;this.Id=this.Nc()-b}ab(){if(this.B)try{this.B.stop(0)}catch(h){}this.Y=!0;this.X=!1;this.Ra=-1}Zb(){this.X||this.Y||this.qa()||(this.ia=this.Cb(!0),this.sa&&(this.ia%=this.Qa()),this.X=!0,this.B.stop(0))}Wc(){!this.X||this.Y||this.qa()||(Y(this),this.B=
this.va().createBufferSource(),this.B.buffer=this.ga.Ja,this.B.connect(this.ha),this.bc=this.B,this.B.onended=this.Cd,this.B.loop=this.sa,this.hd(),this.Fb(),this.Id=this.Nc()-this.ia/(this.Da||.001),this.B.start(0,this.ia),this.X=!1)}Xd(){return super.Xd()*this.ef}gd(){this.ef=this.Jb||this.Tc()?0:1;this.hd()}ie(h){h=!!h;this.sa!==h&&(this.sa=h,this.B&&(this.B.loop=h))}Fb(){let h=this.Da;this.Ye&&(h*=this.A.Jd);this.B&&(this.B.playbackRate.value=h)}ge(h){this.Y||this.qa()||(this.X?this.ia=h:(this.Zb(),
this.ia=h,this.Wc()))}Yd(){return this.ia}je(h){h?this.IsPlaying()?(this.Va=!0,this.ia=this.Cb(!0),this.sa&&(this.ia%=this.Qa()),this.B.stop(0)):this.Va=!1:this.Va&&(Y(this),this.B=this.va().createBufferSource(),this.B.buffer=this.ga.Ja,this.B.connect(this.ha),this.bc=this.B,this.B.onended=this.Cd,this.B.loop=this.sa,this.hd(),this.Fb(),this.Id=this.Nc()-this.ia/(this.Da||.001),this.B.start(0,this.ia),this.Va=!1)}ve(h){super.ve(h);this.ia=h.resumePosition}};"use strict";
{class h{constructor(a){this.A=a;this.o=a.va();this.kc=-1;this.oa=this.$="";this.s=null}l(){this.o=null}Sk(a){this.kc=a}bl(a){this.$=a}G(){return this.o.createGain()}ka(){}pa(){}F(a,b,g,k){a.cancelScheduledValues(0);if(0===k)a.value=b;else{var w=this.o.currentTime;k+=w;switch(g){case 0:a.setValueAtTime(b,k);break;case 1:a.setValueAtTime(a.value,w);a.linearRampToValueAtTime(b,k);break;case 2:a.setValueAtTime(a.value,w),a.exponentialRampToValueAtTime(b,k)}}}Vb(){return{type:this.oa,tag:this.$,params:this.s}}}
self.kh=class extends h{constructor(a,b,g,k,w,n,e){super(a);this.oa="filter";this.s=[b,g,k,w,n,e];this.D=this.G();this.h=this.G();this.h.gain.value=e;this.g=this.G();this.g.gain.value=1-e;this.K=this.o.createBiquadFilter();this.K.type=b;this.K.frequency.value=g;this.K.detune.value=k;this.K.Q.value=w;this.K.gain.vlaue=n;this.D.connect(this.K);this.D.connect(this.g);this.K.connect(this.h)}l(){this.D.disconnect();this.K.disconnect();this.h.disconnect();this.g.disconnect();super.l()}pa(a){this.h.disconnect();
this.h.connect(a);this.g.disconnect();this.g.connect(a)}ka(){return this.D}ya(a,b,g,k){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.s[5]=b;this.F(this.h.gain,b,g,k);this.F(this.g.gain,1-b,g,k);break;case 1:this.s[1]=b;this.F(this.K.frequency,b,g,k);break;case 2:this.s[2]=b;this.F(this.K.detune,b,g,k);break;case 3:this.s[3]=b;this.F(this.K.Q,b,g,k);break;case 4:this.s[4]=b,this.F(this.K.gain,b,g,k)}}};self.ih=class extends h{constructor(a,b,g,k){super(a);this.oa="delay";this.s=[b,g,k];this.D=
this.G();this.h=this.G();this.h.gain.value=k;this.g=this.G();this.g.gain.value=1-k;this.tc=this.G();this.ra=this.o.createDelay(b);this.ra.delayTime.value=b;this.ec=this.G();this.ec.gain.value=g;this.D.connect(this.tc);this.D.connect(this.g);this.tc.connect(this.h);this.tc.connect(this.ra);this.ra.connect(this.ec);this.ec.connect(this.tc)}l(){this.D.disconnect();this.h.disconnect();this.g.disconnect();this.tc.disconnect();this.ra.disconnect();this.ec.disconnect();super.l()}pa(a){this.h.disconnect();
this.h.connect(a);this.g.disconnect();this.g.connect(a)}ka(){return this.D}ya(a,b,g,k){const w=self.Pa.Ef;switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.s[2]=b;this.F(this.h.gain,b,g,k);this.F(this.g.gain,1-b,g,k);break;case 4:this.s[1]=w(b);this.F(this.ec.gain,w(b),g,k);break;case 5:this.s[0]=b,this.F(this.ra.delayTime,b,g,k)}}};self.hh=class extends h{constructor(a,b,g,k){super(a);this.oa="convolution";this.s=[g,k];this.pg=this.og="";this.D=this.G();this.h=this.G();this.h.gain.value=k;this.g=
this.G();this.g.gain.value=1-k;this.dc=this.o.createConvolver();this.dc.normalize=g;this.dc.buffer=b;this.D.connect(this.dc);this.D.connect(this.g);this.dc.connect(this.h)}l(){this.D.disconnect();this.dc.disconnect();this.h.disconnect();this.g.disconnect();super.l()}pa(a){this.h.disconnect();this.h.connect(a);this.g.disconnect();this.g.connect(a)}ka(){return this.D}ya(a,b,g,k){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.s[1]=b,this.F(this.h.gain,b,g,k),this.F(this.g.gain,1-b,g,k)}}Nk(a,
b){this.og=a;this.pg=b}Vb(){const a=super.Vb();a.bufferOriginalUrl=this.og;a.bufferUrl="";a.bufferType=this.pg;return a}};self.lh=class extends h{constructor(a,b,g,k,w,n){super(a);this.oa="flanger";this.s=[b,g,k,w,n];this.D=this.G();this.g=this.G();this.g.gain.value=1-n/2;this.h=this.G();this.h.gain.value=n/2;this.hc=this.G();this.hc.gain.value=w;this.ra=this.o.createDelay(b+g);this.ra.delayTime.value=b;this.I=this.o.createOscillator();this.I.frequency.value=k;this.Z=this.G();this.Z.gain.value=g;
this.D.connect(this.ra);this.D.connect(this.g);this.ra.connect(this.h);this.ra.connect(this.hc);this.hc.connect(this.ra);this.I.connect(this.Z);this.Z.connect(this.ra.delayTime);this.I.start(0)}l(){this.I.stop(0);this.D.disconnect();this.ra.disconnect();this.I.disconnect();this.Z.disconnect();this.g.disconnect();this.h.disconnect();this.hc.disconnect();super.l()}pa(a){this.h.disconnect();this.h.connect(a);this.g.disconnect();this.g.connect(a)}ka(){return this.D}ya(a,b,g,k){switch(a){case 0:b=Math.max(Math.min(b/
100,1),0);this.s[4]=b;this.F(this.h.gain,b/2,g,k);this.F(this.g.gain,1-b/2,g,k);break;case 6:this.s[1]=b/1E3;this.F(this.Z.gain,b/1E3,g,k);break;case 7:this.s[2]=b;this.F(this.I.frequency,b,g,k);break;case 8:this.s[3]=b/100,this.F(this.hc.gain,b/100,g,k)}}};self.nh=class extends h{constructor(a,b,g,k,w,n,e){super(a);this.oa="phaser";this.s=[b,g,k,w,n,e];this.D=this.G();this.g=this.G();this.g.gain.value=1-e/2;this.h=this.G();this.h.gain.value=e/2;this.K=this.o.createBiquadFilter();this.K.type="allpass";
this.K.frequency.value=b;this.K.detune.value=g;this.K.Q.value=k;this.I=this.o.createOscillator();this.I.frequency.value=n;this.Z=this.G();this.Z.gain.value=w;this.D.connect(this.K);this.D.connect(this.g);this.K.connect(this.h);this.I.connect(this.Z);this.Z.connect(this.K.frequency);this.I.start(0)}l(){this.I.stop(0);this.D.disconnect();this.K.disconnect();this.I.disconnect();this.Z.disconnect();this.g.disconnect();this.h.disconnect();super.l()}pa(a){this.h.disconnect();this.h.connect(a);this.g.disconnect();
this.g.connect(a)}ka(){return this.D}ya(a,b,g,k){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.s[5]=b;this.F(this.h.gain,b/2,g,k);this.F(this.g.gain,1-b/2,g,k);break;case 1:this.s[0]=b;this.F(this.K.frequency,b,g,k);break;case 2:this.s[1]=b;this.F(this.K.detune,b,g,k);break;case 3:this.s[2]=b;this.F(this.K.Q,b,g,k);break;case 6:this.s[3]=b;this.F(this.Z.gain,b,g,k);break;case 7:this.s[4]=b,this.F(this.I.frequency,b,g,k)}}};self.mh=class extends h{constructor(a,b){super(a);this.oa="gain";this.s=
[b];this.v=this.G();this.v.gain.value=b}l(){this.v.disconnect();super.l()}pa(a){this.v.disconnect();this.v.connect(a)}ka(){return this.v}ya(a,b,g,k){const w=self.Pa.Ef;switch(a){case 4:this.s[0]=w(b),this.F(this.v.gain,w(b),g,k)}}};self.ph=class extends h{constructor(a,b,g){super(a);this.oa="tremolo";this.s=[b,g];this.v=this.G();this.v.gain.value=1-g/2;this.I=this.o.createOscillator();this.I.frequency.value=b;this.Z=this.G();this.Z.gain.value=g/2;this.I.connect(this.Z);this.Z.connect(this.v.gain);
this.I.start(0)}l(){this.I.stop(0);this.I.disconnect();this.Z.disconnect();this.v.disconnect();super.l()}pa(a){this.v.disconnect();this.v.connect(a)}ka(){return this.v}ya(a,b,g,k){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.s[1]=b;this.F(this.v.gain.value,1-b/2,g,k);this.F(this.Z.gain.value,b/2,g,k);break;case 7:this.s[0]=b,this.F(this.I.frequency,b,g,k)}}};self.oh=class extends h{constructor(a,b,g){super(a);this.oa="ringmod";this.s=[b,g];this.D=this.G();this.h=this.G();this.h.gain.value=
g;this.g=this.G();this.g.gain.value=1-g;this.Fc=this.G();this.Fc.gain.value=0;this.I=this.o.createOscillator();this.I.frequency.value=b;this.I.connect(this.Fc.gain);this.I.start(0);this.D.connect(this.Fc);this.D.connect(this.g);this.Fc.connect(this.h)}l(){this.I.stop(0);this.I.disconnect();this.Fc.disconnect();this.D.disconnect();this.h.disconnect();this.g.disconnect();super.l()}pa(a){this.h.disconnect();this.h.connect(a);this.g.disconnect();this.g.connect(a)}ka(){return this.D}ya(a,b,g,k){switch(a){case 0:b=
Math.max(Math.min(b/100,1),0);this.s[1]=b;this.F(this.h.gain,b,g,k);this.F(this.g.gain,1-b,g,k);break;case 7:this.s[0]=b,this.F(this.I.frequency,b,g,k)}}};self.jh=class extends h{constructor(a,b,g,k,w,n){super(a);this.oa="distortion";this.s=[b,g,k,w,n];this.D=this.G();this.Ed=this.G();this.Dd=this.G();this.Ok(k,w);this.h=this.G();this.h.gain.value=n;this.g=this.G();this.g.gain.value=1-n;this.Nd=this.o.createWaveShaper();this.Le=new Float32Array(65536);this.mj(b,g);this.Nd.curve=this.Le;this.D.connect(this.Ed);
this.D.connect(this.g);this.Ed.connect(this.Nd);this.Nd.connect(this.Dd);this.Dd.connect(this.h)}l(){this.D.disconnect();this.Ed.disconnect();this.Nd.disconnect();this.Dd.disconnect();this.h.disconnect();this.g.disconnect();super.l()}Ok(a,b){.01>a&&(a=.01);this.Ed.gain.value=a;this.Dd.gain.value=Math.pow(1/a,.6)*b}mj(a,b){for(let g=0;32768>g;++g){let k=g/32768;k=this.dl(k,a,b);this.Le[32768+g]=k;this.Le[32768-g-1]=-k}}dl(a,b,g){g=1.05*g*b-b;const k=0>a?-a:a;return(k<b?k:b+g*self.Pa.wl(k-b,1/g))*(0>
a?-1:1)}pa(a){this.h.disconnect();this.h.connect(a);this.g.disconnect();this.g.connect(a)}ka(){return this.D}ya(a,b,g,k){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.s[4]=b,this.F(this.h.gain,b,g,k),this.F(this.g.gain,1-b,g,k)}}};self.gh=class extends h{constructor(a,b,g,k,w,n){super(a);this.oa="compressor";this.s=[b,g,k,w,n];this.v=this.o.createDynamicsCompressor();this.v.threshold.value=b;this.v.knee.value=g;this.v.ratio.value=k;this.v.attack.value=w;this.v.release.value=n}l(){this.v.disconnect();
super.l()}pa(a){this.v.disconnect();this.v.connect(a)}ka(){return this.v}ya(){}};self.fh=class extends h{constructor(a,b,g){super(a);this.oa="analyser";this.s=[b,g];this.v=this.o.createAnalyser();this.v.fftSize=b;this.v.smoothingTimeConstant=g;this.ug=new Float32Array(this.v.frequencyBinCount);this.Mg=new Uint8Array(b);this.Kg=this.Nb=0;this.A.Ti(this)}l(){this.A.Dk(this);this.v.disconnect();super.l()}la(){this.v.getFloatFrequencyData(this.ug);this.v.getByteTimeDomainData(this.Mg);const a=this.v.fftSize;
let b=this.Nb=0;for(var g=0;g<a;++g){let k=(this.Mg[g]-128)/128;0>k&&(k=-k);this.Nb<k&&(this.Nb=k);b+=k*k}g=self.Pa.di;this.Nb=g(this.Nb);this.Kg=g(Math.sqrt(b/a))}pa(a){this.v.disconnect();this.v.connect(a)}ka(){return this.v}ya(){}Kh(){return{tag:this.$,index:this.kc,peak:this.Nb,rms:this.Kg,binCount:this.v.frequencyBinCount,freqBins:this.ug}}}};